### ISSUE TITLE
Change attributes on 'autoLink' generated <a> tags

### ISSUE THREAD

**Issue by saneef** [tiff/wysihtml5#102]
Is there any config or events I can use to change the attributes of the `<a>` tags which are generated when `autoLink: true`?
### Example

If I type in an URL `www.example.com` it generates the tag `<a href="http://www.example.com">www.example.com</a>`. 

But some cases I require add extra attributes like `target="_blank"` etc.

**Comment by tiff** [comment]
That's already done. Check the resulting HTML!
The magic lies within the used parser rules:
https://github.com/xing/wysihtml5/blob/master/parser_rules/advanced.js#L179

It sets `target="_blank"` and `rel="nofollow"` on the anchor.

The parser rules are applied when the user changes to the HTML view or right before the html is submitted to the server.

**Comment by saneef** [comment]
@tiff In my usage, I'm not using a form. So is there a way I can invoke this parsing?

**Comment by jordandh** [comment]
@saneef did you find a way to invoke parsing? I have the same situation where I am not using a form to submit. @tiff is this possible?

**Comment by jordandh** [comment]
After some further research I have found that editor.getValue(true) is what I needed. I was not passing true when I grabbed the value. Sorry to waste anyone's time asking the question but maybe someone else with the same problem will see this :)
