### ISSUE TITLE
Arbitrary foreColor / font color?

### ISSUE THREAD

**Issue by roccogliffy** [tiff/wysihtml5#103]
My project requires that we use a colorpicker for font color, and that we pass in an arbitrary color value to our RTE (ex #ff00ff).  Is there a mechanism for this, or do you have any suggestions on how to modify our code locally to add this feature?

**Comment by tiff** [comment]
You would need to have a css class for each color. So no, it's not possible and probably will never be. You can try to translate the hex-code to the nearest supported color. Does that help?

**Comment by roccogliffy** [comment]
Hi, thanks for your reply.  I understand your philosophy of using no inline-styles for your library, but that doesn't really fit the requirements of my project.  In the end, I'll probably need to use a different lib with inline styles.  Good luck!
