### ISSUE TITLE
Using javascript to count the number of characters in textarea doesn't work

### ISSUE THREAD

**Issue by RoyLee** [tiff/wysihtml5#104]
I've been trying to create a character counter for the html in the textarea editor by creating a JQuery keyup function:

```
var editor = new wysihtml5.Editor("wysihtml5_textarea",
{toolbar: "wysihtml5_editor_toolbar",
stylesheets: '/stylesheets/wysihtml5_editor.css',
parserRules: wysihtml5ParserRules,
supportTouchDevices: true});

var wysihtml5_cur_length = 0;

function verifyWysihtml5CurLength()
{
  wysihtml5_cur_length = $('#wysihtml5_textarea').val().length;
  alert(wysihtml5_cur_length);
}  

editor.on("change:composer", verifyWysihtml5CurLength); //works for the composer area
editor.on("change:textarea", verifyWysihtml5CurLength);  //does not work for the html textarea
```

This does not recognize any keyups in the html textarea where text is typed.  It does recognize keyups in the "change:composer" area.

Should I be counting another place other than $('#wysihtml5_textarea')?

I've also tried: document.getElementsByClassName('wysihtml5-sandbox')[0].contentWindow.document.body.innerHTML.length

**Comment by tiff** [comment]
Closing this since this got solved in a private conversation :)

Solution is to not listen on the textarea for keyup events but instead on the `<iframe>`'s body

**Comment by bootstraponline** [comment]
For future readers, this jQuery code works.

`$(editor.composer.element).bind('keyup', function(){ console.log('up') });`

**Comment by Bratzilla** [comment]
@bootstraponline I couldn't get the above line to work for me. The following however seems to be working well (tested on the latest editor version):

```
    editor.observe("load", function() {
            editor.composer.element.addEventListener("keyup", function() {
                    // enter your listener-triggered code or function call here
            });
            });
```

**Comment by bootstraponline** [comment]
That's great you found something that works. The code worked for me when I posted it. [livepreview_wysi](https://github.com/bootstraponline/livepreview_wysi) ended up not binding on keyup for wysihtml5 so I removed that bit of code.

**Comment by ditikos** [comment]
@bootstraponline, where do I put the code @Bratzilla posted? I have a var editor = $("#textarea1").wysihtml5();  on my code. I am using the boostrap-wysihtml5 version.

**Comment by bootstraponline** [comment]
@ditikos You might need something like `var editor = new wysihtml5.Editor` as in the [simple example](http://xing.github.com/wysihtml5/examples/simple.html). Once the editor works then @Bratzilla's code should function.

**Comment by kurtfunai** [comment]
@Bratzilla's approach worked great

**Comment by ghost** [comment]
I struggled with this for a while and ended up using the following in case anybody else is having trouble as well:

```
        $('#textarea').wysihtml5({
            events: {
                load: function() {
                    var some_wysi = $('#textarea').data('wysihtml5').editor;
                    $(some_wysi.composer.element).bind('keyup', function(){ 
                        $('#textarea-preview-div').html(about_editor.getValue(true));
                    });
                }
            }
        });
```
