### ISSUE TITLE
Insert image not updated

### ISSUE THREAD

**Issue by rejeep** [tiff/wysihtml5#105]
Hi,

I'm trying to programmatically insert an image to the textarea when an image is clicked. The code I use looks something like this:

```
jQuery(function() {
  var textarea = $('#page_content');
  if (textarea.length > 0) {
    var editor = textarea.wysihtml5().data('wysihtml5').editor;
    var insertImage = function(img) {
      editor.composer.commands.exec('insertImage', $(img).data('src'));
    };
    $('#images img').click(function() {
      insertImage(this);
    });
  }
});
```

It looks like it works fine and I can see the image, but when I look at the `textarea` contents (Chrome inspector), I see this:

```
<img alt=\"\"><img alt=\"\"><br>
```

Am I missing something?

**Comment by tiff** [comment]
This is fixed in the current master (you just have to compile it or wait for v0.4)

**Comment by rejeep** [comment]
Same issue when compiling master...

**Comment by evadnoob** [comment]
Agree, having the same issue and my <img> tags look like: 

```
<img alt="">
```

I'll add that the image tag seems to work when inserting via command, but then doesn't work if I make a new editor out of the existing html.

I put a screenshot up: http://www.flickr.com/photos/evadnoob/7510286288/

**Comment by evadnoob** [comment]
For now I've worked around this issue by forcing the editor to have the same text as the "textarea":
The setTimeout is used to make this call happen after the current event loop is executed:

``` javascript
    setTimeout( function() {
      $(needsEditor).data('wysihtml5').editor.setValue(model.get('text'));
    });
```

**Comment by tiff** [comment]
@evadnoob and @rejeep: Are you using the compiled master + the parser_rules from master?

**Comment by nicinabox** [comment]
~~+1 also having this issue with 0.3.0 from the master branch.~~

Just compiled from master (version number doesn't change) and it works correctly.

**Comment by martin-g** [comment]
I'm using a build from master (wysihtml5-0.4.0pre.js) with bootstrap-wysihtml5.js (again from its master) and I'm experiencing the same problem.
It seems attributeCheckMethods's 'url' and 'src' work with fully absolute (scheme://) or context absolute (/some/url) but both do not allow relative urls like '../some/url'.
Is there a reason why 'src' doesn't support such relative urls ?
