### ISSUE TITLE
HTML preview in Editor Example

### ISSUE THREAD

**Issue by conartist6** [tiff/wysihtml5#107]
Given the number of people forking the code it would be pretty useful if it was possible to see the HTML generated by the editor in a live preview on the example page. I made such a thing for myself, but I couldn't figure out how to do it without making changes to a few event handlers...

**Comment by tiff** [comment]
You can generate a live preview by yourself easily.

``` javascript
var preview = document.getElementById("live-preview"); // <textarea> where you want to show the generated html
setInterval(function() {
  preview.value = myEditor.getValue(true);
}, 500);
```

I don't see a reason why this should be part of wysihtml5. :) 
Hope this helps!

**Comment by conartist6** [comment]
Probably should have thought of just polling it. Thanks!

**Comment by hyperrjas** [comment]
+1 Something like https://github.com/samwillis/pagedown-bootstrap

Thank you!
