### ISSUE TITLE
Aggressive renaming in formatBlock

### ISSUE THREAD

**Issue by abhaga** [tiff/wysihtml5#108]
In the formatBlock command, whenever an ancestor is found that can be renamed, it is used instead of inserting a new block level tag. The comments say that it is to avoid generating nested headings which is invalid.

However, this allows makes it impossible to insert a 'p' tag inside a 'div'. Issuing a formatBlock command on some selected text inside a div, changes the complete 'div' to a 'p'. Similarly, inserting a heading inside a 'div' is impossible.

My questions is: is that the intended behavior for WYSIHTML5? Or would you consider a more nuanced implementation of formatBlock?

**Comment by tiff** [comment]
Hi @abhaga,

wysihtml5 should stay very simple. I don't think that nested block elements will ever be supported.
If you wanna work on a fork where this is possible then consider this hint:
You basically just have to change this:
https://github.com/xing/wysihtml5/blob/master/src/commands/formatBlock.js#L8

Looking forward! :)
Thanks.
