### ISSUE TITLE
Bold formatting can be erratic at times

### ISSUE THREAD

**Issue by mrkipling** [tiff/wysihtml5#109]
To reproduce, load a fresh editor (e.g. http://xing.github.com/wysihtml5/examples/simple.html) and:
1. make the text bold, type a line of text, press enter
2. make the text not bold, type another line of text, press enter
3. type another line of text

You would expect line 3 to not be bold, as you turned bold off at the beginning of line 2 and haven't turned it back on, however this is not the case (it turns itself back on unexpectedly).

**Comment by abhaga** [comment]
Reproducible on Chrome. Works as expected on FF 13.

**Comment by tiff** [comment]
Weird... will look into this. Don't think I'm able to fix this until v0.4. Scheduled for v0.5. Thanks!

**Comment by mrkipling** [comment]
Thanks! And apologies for not specifying which browser I was using.
