### ISSUE TITLE
After inserting a block element, new lines are generated using DIVs, not BRs

### ISSUE THREAD

**Issue by javan** [tiff/wysihtml5#11]
When normally entering text, pressing enter generates a `<br>`, but after inserting a block element (I tried lists and headers), newlines are created by wrapping the text in a `div`. Any idea what's up here?

Type lines of text normally:

``` html
line one<br>line two<br>line three
```

Typing lines of text after a list:

``` html
<ul><li>one</li><li>two</li></ul><div>line one</div><div>line two</div><div>line three</div>
```

**Comment by tiff** [comment]
I think I fixed it with https://github.com/xing/wysihtml5/commit/b44f7bd775eb1392339b6f1381e92acaacb38d4a
Please check :)

I'm planning to work on some issues and release v0.3.0 later this week.

**Comment by javan** [comment]
Yup, looks good over here. Thanks!
