### ISSUE TITLE
show:dialog being fired on dialog save

### ISSUE THREAD

**Issue by kagd** [tiff/wysihtml5#111]
When saving a dialog entry, show:dialog event is being fired. show:dialog occurs before save:dialog is fired.

**Comment by tiff** [comment]
Hey @kagd,

sorry but I do not understand what you mean.
I checked the code and everything makes sense.
I'm even not able to reproduce this...

**Comment by kagd** [comment]
Sorry for the confusion. I should have written a bit more of a description. Here is how I am able to reproduce the issue.

From the [demo](http://xing.github.com/wysihtml5/examples/advanced.html) page:
1. Open up a javascript console.
2. type: `editor.on('save:dialog', function(){ console.log('save'); }).on('show:dialog', function(){ console.log('show'); } )`
3. Open the 'insert link' dialog
4. Type anything and click OK

At this point, within the js console, you should `show` twice and `save` once.
