### ISSUE TITLE
'element' undefined, line 4590, several versions.

### ISSUE THREAD

**Issue by i-make-robots** [tiff/wysihtml5#112]
I've tried 2.0, 2.0-min, 3.0, 3.0-rc3.  Firefox on OSX Lion hates all versions.  The line in question is

```
after: function(element) {
  element.parentNode.insertBefore(elementToInsert, element.nextSibling);
}
```

I tried

```
after: function(element) {
  if(element!= undefined) element.parentNode.insertBefore(elementToInsert, element.nextSibling);
}
```

which makes the error go away but doesn't produce the wysiwyg editor.  I'm also loading jQuery 1.7.2, Bootstrap 2.0, and I'm trying to use bootstrap-wysihtml5.  I'm calling 

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script src="./bootstrap/js/wysihtml5-0.3.0_rc3.js"></script>
<script src="./bootstrap/js/bootstrap-wysihtml5.js"></script>
<script type='text/javascript'>
$('textarea').wysihtml5();
</script>
```

Please let me know what I'm doing wrong.

**Comment by tiff** [comment]
Can it be that you didn't create a textarea?
wysihtml5 takes a textarea and transforms it into an editor.

**Comment by i-make-robots** [comment]
Yes, I am creating several textareas.  Maybe it's the more-than-one that's breaking it?

**Comment by renaudleo** [comment]
I would guess it's only because your code is executed before the domready event. Is that code in the `<head>` or before the closing of your `<body>`?

**Comment by i-make-robots** [comment]
nm, my apologies.

**Comment by i-make-robots** [comment]
yes, it is before the closing of body.  I have a single textarea.  When I try

```
$('.textarea').wysihtml5();
```

or

```
$('textarea').wysihtml5();
```

it fails, but

```
$('#textarea').wysihtml5();
```

works for a single element.

**Comment by tiff** [comment]
Just checked the bootstrap-wysihtml5 repo and saw that every textarea needs to have an id...

**Comment by i-make-robots** [comment]
dang.  sorry for all the trouble !

**Comment by tiff** [comment]
I created a pull request in the bootstrap-wysihtml5 repo https://github.com/jhollingworth/bootstrap-wysihtml5/pull/63
