### ISSUE TITLE
Text align center problem in textarea

### ISSUE THREAD

**Issue by donatasbartus** [tiff/wysihtml5#116]
Hello,

I have an issue with "wysiwyg-text-align-center" div inside text area. 

As I use the command "justifyCenter" on the toolbar, it ads the div inside the textarea, after I save the content, it's ok on the front end, but in textarea it's still aligned by left. How could it be fixed? 

Thank you

**Comment by donatasbartus** [comment]
Hi guys,

An update for this issue. It seems i've used the wrong stylesheet.... 
Anyway it's working fine now on Firefox, but Chrome seems not to load the stylesheet which is described in:
stylesheets: ["/js/wysihtml5/editor.css"]

For testing i've added H1 style font-size:55px; Firefox shows different size, align to right, center. But Chrome doesn't. I've tried removing all other stylesheets, still no luck.

My complete JS code for loading editor:

``` javascript
<script>
          var editor = new wysihtml5.Editor("textarea", {
            toolbar:      "wsbEditorToolbar",
            autoLink:             true,
            composerClassName:    "wysihtml5-editor",           
            parserRules:  wysihtml5ParserRules,
            allowObjectResizing:  true,
            stylesheets: ["/js/wysihtml5/editor.css"]
          });
</script>
```

How to fix it on Chrome?

Thanks for help.

**Comment by tiff** [comment]
Hey @DonatasB,

I can't reproduce this behavior. In my demos the stylesheet always loads correctly in chrome.
Maybe chrome cached your stylesheet? Clear your cache and try again. Also can you check whether the stylesheet shows up in the network tab of your chrome developer tools?
Thanks!

**Comment by Bratzilla** [comment]
@tiff - I am definitely getting some style "weirdness". 

The editor style sheet is loading normally, and the text alignment styles seem to work just fine on regular block-level elements.

However, I cannot get centering or right-alignment to work within the textareas of either Chrome or Firefox. I'm testing the editor on forms and not directly in-line, and will continue tests later today. Right now, I can confirm that neither centering nor right align appear to work in the textareas of Chrome and Firefox (though the styles indeed do work when applied to paragraphs, etc., that are not in the textarea).

**Comment by donatasbartus** [comment]
Hi @Bratzilla,

I have solved this issue. The problem was for me, that i was using it in Jquery block UI window, and Firebug did not show any errors while loading the editor. Finally using Chrome developer tools I found out that loaders CSS file is not loaded. 

That was my case, as soon as I fixed that Editor works just fine!

Hope this helps to you.

**Comment by Bratzilla** [comment]
Hi there, @DonatasB.

Thanks for the tip! Unfortunately, this is not my case, as I am testing with pure HTML forms and jQuery. 

I even added justifyCenter to the examples that come with the distribution, and centering doesn't seem to work in those files either.

Ironically, my main project (which is why I am evaluating this editor) does indeed use JQuery UI quite prominently, so it's good to know this is another potential gotcha.

**Comment by Bratzilla** [comment]
@tiff , @DonatasB

RESOLVED!!!

After reading what's posted here again (after a couple of cups of coffee) I found my error.

The iframe was NOT getting the proper style. I tweaked my link, and, sure enough, formatting is now working like a charm!!!

Thank you again for the information!

I'll keep testing and let you know if there are any issues.
