### ISSUE TITLE
Populate with text once editor initalised.

### ISSUE THREAD

**Issue by oller** [tiff/wysihtml5#118]
Hi guys,

I'm trying to populate the wysihtml5 editor with a string once it's been loaded.

I've done this in a roundabout way:

 $('iframe').contents().find('.wysihtml5-editor').html('I will appear in the editor');

I can't find it in the documentation, but presume there's a method already existing and a bit tidier to populate to editor with a string?

Any suggestions, to improve this?

Many thanks

**Comment by Mipme** [comment]
It's simply

```
yourWysihtmlEditorInstance.setValue(html [[, parse = (true|false)]])
```

second param is if the value shall be parsed / sanitised or not...

**Comment by oller** [comment]
Hi thanks for your quick helpful reply.

That kind of works, it sets the content within the hidden [textarea] tags however the content of the wysihtml5 editor remains untouched.  likewise getValue() seems to return that content of the hidden [textarea] and not the wysihtml5 editor.

Am I missing a trick here?  Is there something I need to call to refresh the content over to the editor, or have I not initialised something propertly?  The editor itself is displaying and behaving fine

**Comment by tiff** [comment]
Hi @oller,

I can't reproduce your problem. If I go to the demo (http://xing.github.com/wysihtml5/examples/advanced.html) and execute ...

``` javascript
editor.setValue("foobar");
```

... then the editor gets updated and shows "foobar".

**Comment by oller** [comment]
You are entirely right, thank you @tiff 

Sorry, I was barking up the wrong tree.

I am using http://jhollingworth.github.com/bootstrap-wysihtml5/ to extend the already excellent wysihtml5 library.  Which I can see initiates the editors differently and claims the editor object can be accessed via:

$('#textarea-id').wysihtml5().data("wysihtml5").editor.setValue('test');

It is this function, which produced the behaviour explained above.

I appreciate this isn't an issue with this library, but just wanted to tie up the loose end.

**Comment by nadimkobeissi** [comment]
Why isn't this very essential feature mentioned in the documentation?

**Comment by zabinet** [comment]
Hugely helpful. Thanks @oller for providing an answer as well. I agree with @kaepora.  Amazing this isn't documented.

**Comment by Dynalon** [comment]
+1 for documenting this. very helpful.
