### ISSUE TITLE
Doesn't permit embedding/upload of local image files

### ISSUE THREAD

**Issue by metalhaze** [tiff/wysihtml5#122]
You need a way to allow access to your local file system on PC or mobile device to insert an image. Apple will be adding media upload functionality to their OS in iOS 6.

http://www.idownloadblog.com/2012/06/13/ios-6-safari-media-uploads/

**Comment by appastair** [comment]
Do you mean using it as a local editor - not uploading the file to the script's server? i.e. src=/home/user/local.png

_Sent via Hubroid_

**Comment by tiff** [comment]
Hey @metalhaze,

wysihtml5 is a pure client side library. Implementing an upload feature which requires some sort of server side logic is not an option.
This doesn't mean that wysihtml5 doesn't work well with images from the local file system. You have to build the upload functionality yourself and insert the uploaded image into the editor afterwards.

Something like:

``` javascript
var editor = new wysihtml5.Editor(myTextarea);

whenTheUserUploadedAnImage(function(url) {
  editor.composer.commands.exec("insertImage", url);
});
```
