### ISSUE TITLE
How to clear textarea.

### ISSUE THREAD

**Issue by berpcor** [tiff/wysihtml5#128]
Need to remove value of textarea, but I can't. How to do that?

// Init
$('#description').wysihtml5();

$('$description').val(''); - doesn't work.

**Comment by Mipme** [comment]
To clear the editor:

```
  var rte = $('#description').wysihtml5();
  rte.setValue('');
```

**Comment by berpcor** [comment]
No, it doesn't work...

**Comment by tiff** [comment]
This will work:

```
  $('#description').data("wysihtml5").editor.clear();
```

**Comment by seppludger** [comment]
Great. Thx.

**Comment by abra-chan** [comment]
Thanks @tiff! That was super helpful.

**Comment by luizcarvalho** [comment]
Realy Great! Tnks @tiff

**Comment by rwilsonjr** [comment]
This no longer works.

**Comment by an-sangkil** [comment]
Thanks @tiff  very good!!

**Comment by tyganeshbabu** [comment]
$('.editor_note').data("wysihtml5").editor.clear(); This doesn't work...

**Comment by zedtux** [comment]
> $('.editor_note').data("wysihtml5").editor.clear(); This doesn't work...

Not true, It is working.

**Comment by quantumsized** [comment]
For me, I've found just specifying editor.clear();  works exactly the same as editor.setValue(); and editor.setValue('');  and they all work fine.  Using chrome

**Comment by srikanthjeeva** [comment]
When I use 

``` javascript
$('#comments').data("wysihtml5").editor.clear();
```

I'm getting this error. 

 **Uncaught TypeError: Cannot read property 'editor' of undefined**

**Comment by quantumsized** [comment]
I have found if you are just trying to clear the editor, you can simply 
use _editor.clear();_
So what you have there is using a selector... If this is in a modal or 
just in the window, you could do _$('#comments').editor.clear();_

The first one will clear all wysihtml5 editors loaded in the window and 
the other will be specific to "comments"
What I would do is have the textarea that has the wysihtml5 editor 
attached inside a div with the id or class assigned and then use 
_$('#comments').editor.clear();_ "comments" would be the id in this case.
That way is it specific to that editor that is loaded to that textarea.

All the best.

**Comment by haidarvm** [comment]
Please tell me how to reset or clear the textarea issue , i did on chrome, firefox, and opera Not work

``` $('#description').data("wysihtml5").editor.clear();
$('#description').data("wysihtml5").editor.setValue('');
$('.textarea').data("wysihtml5").editor.clear();
$('.textarea').data("wysihtml5").editor.setValue('');
$('#description').editor.clear();
```

**Comment by tienhien1102** [comment]
the simple way:
$('form')[0].reset();

**Comment by smsgatewaycenter** [comment]
This worked for me:
`$("#description").html("");`
