### ISSUE TITLE
BBCodes Support

### ISSUE THREAD

**Issue by rafadizeo** [tiff/wysihtml5#129]
Sorry for my english, is too bad...

First, thank to all team members of this fantastic and beautiful editor...

I want integrate this editor  to my web in SMF (Simple Machines Forum). That work only with BBC

How i can do this ?

its possible change html tags to bbc tags

example: <_b></_b> to [b][/b]

i dont wanna use converters and parser i want do this manually

**Comment by tiff** [comment]
In general this requires some effort. It's not on my list to integrate BBCode to wysihtml5. Check #92 to get some hints on how you could add bbcode support to wysihtml5.
