### ISSUE TITLE
commands eventually make the composer lose selection

### ISSUE THREAD

**Issue by haggen** [tiff/wysihtml5#131]
I really don't if I just didn't notice until now, or it wasn't happening before but today I noticed that sometimes - pretty frequently - when executing a command (clicking the toolbar button or using the shortcut) the composes loses selection before the command is applied, but the corresponding tags shows up at the beginning at the selection, like this:

Supose you have "Lorem ipsum dolor sit amet" in your editor; you double click "ipsum" for you want to make it bold; then you click at the bold command button; suddenly your editor loses selection and nothing happens but if you take a look at the source `<b></b>` appears right before the part you selected, like this: "Lorem <b></b>isum dolor sit amet". And that's where the caret appear after losing selection.

I'm using Chrome Version 19.0.1084.56 on OSX.

It happens with bold, italic and even my custom `formatInline` for strike-through.

**Comment by haggen** [comment]
I happened to clone a new repo of yours, ran `make` to update the distributable file and opened `examples/simple.html`. It happend there too.

Make a selection; execute a command, it may work, but sometime it don't; if it works, just try making a new selection in another part of the text; if it don't and you re-select the SAME part, this time it will work.

**Comment by Mipme** [comment]
I've got the same problem in Chrome and Safari for creating a link - makes me go nuts!

**Comment by tiff** [comment]
Thanks will look into this!

**Comment by m4tm4t** [comment]
I'm running the same problem. The selection lose focus, but HTML elements are added at the beginning of selection.

Imagine I want bold "World" in "Hello World", output will be

``` html
Hello <b></b>World
```

Selecting and bold again work:

``` html
Hello <b></b><b>World</b>
```

But, in the demo (latest version) that doesn't happen, why ?

**Comment by tiff** [comment]
@foohey Can you compile (`make`) master and check again. Thanks!

**Comment by m4tm4t** [comment]
Haaaa nice, that work.

The new release will come out soon? I created a Gem to include wysi in my rails app (and I hate dependencies in the app tree)

**Comment by Mipme** [comment]
for the problem was that i had a event listener on change that stored the source and set the content of the editor again via getValue(true) and setValue(true). After removing that its working fine for me...

**Comment by haggen** [comment]
Latest commits seems to have fixed it. I pulled the repo, ran Make and updated my dist file and everything is working fine.

**Comment by tiff** [comment]
Thanks for testing and reporting!
