### ISSUE TITLE
Can the textarea placeholder attribute be changed to data-placeholder?

### ISSUE THREAD

**Issue by RoyLee** [tiff/wysihtml5#133]
I'm currently using Ruby on Rails and it does not allow for custom attributes.  It does allow html5 data attributes.

Thanks!

**Comment by tiff** [comment]
Hi @RoyLee, `placeholder` is not a "custom" attribute. It's a valid html5 attribute on a form elements. Feel free to fork or monkey-patch the code to use a custom `data-placeholder` attribute. :)
