### ISSUE TITLE
Drag and dropping text doesn't move it

### ISSUE THREAD

**Issue by javan** [tiff/wysihtml5#140]
If you select some text and drag it, the cursor doesn't move to your mouse location so dropping the text puts it right back where you started.

**Comment by deepwell** [comment]
Really depends on your browser and how well they have implemented content editable.

Works perfectly in Firefox.
Doesn't work in Chrome, Safari, or IE.
It works in Opera, except that it copy's the text, so you now have the selection in 2 places. Also, another Opera bug: formatting is not copied.

**Comment by javan** [comment]
Thanks @deepwell, sorry I was so brief with my report.
