### ISSUE TITLE
contextual controls

### ISSUE THREAD

**Issue by jancborchardt** [tiff/wysihtml5#146]
The formatting bar in the demo looks really good, but even better would be if it would only appear when needed. Similar to [Etch.js](http://etchjs.com/) and [PopClip](http://pilotmoon.com/popclip/).

Basically, most of the controls only need to be shown when text is selected.

**Comment by tiff** [comment]
Hey @jancborchardt,

I thought about this for a while and came to the conclusion that this shouldn't be part of the core of wysihtml5.
wysihtml5 is a bare bone rich text editor which lets developers on their own decide how the editor and the toolbar looks like. The css and images used in the demo are not part of the wysihtml5 library.

There are other libraries that offer a UI on top of wysihtml5 (eg. [bootstrap-wysihtml5](http://jhollingworth.github.com/bootstrap-wysihtml5/)).

I can imagine a UI library/plugin that brings such a fancy to wysihtml5.
I'd be happy to support the person who volunteers.
The idea is great.

**Comment by jancborchardt** [comment]
Actually, [Hallo.js](http://hallojs.org) by @bergie seems to be perfect for that. And vice versa, Hallo would probably benefit from using wysihtml5.

Do you know each others projects @tiff & @bergie? What do you think?

**Comment by bergie** [comment]
@jancborchardt we considered wysihtml5 as the new editor core for Hallo in bergie/hallo#5

Unfortunately the approaches are not very compatible. Hallo uses contentEditable, so the text being edited stays within the context it is coming from, allowing all CSS rules from the page etc. to apply to it. wysihtml5 uses an IFRAME, so the text is detached from its context.

**Comment by tiff** [comment]
@bergie Bummer. The `<iframe>` is an important part of wysihtml5. I'm closing this. Thanks anyway.
