### ISSUE TITLE
Editor loads incorrectly in ajax generated pages

### ISSUE THREAD

**Issue by daveearley** [tiff/wysihtml5#15]
When trying to initialize the editor withing an ajax generated page the generated iframe is not editable.

**Comment by tiff** [comment]
Could you please provide me with more information (browser version, wysihtml5 version, ...)
Thanks! :)

**Comment by daveearley** [comment]
No problem,

**Browser:** Chrome : 18.0.1025.56 beta-m
**Wysihtml5 Version:** wysihtml5-0.3.0 RC1

Although since I posted the above I have tried jHtmlArea and it appears to have the same problem, therefor I presume it's a browser issue.

**Comment by tiff** [comment]
Ah, ok. Can I see it somewhere in action?

**Comment by daveearley** [comment]
Sorry I'm working on it internally in work at the moment, I can put up a demo tomorrow.

**Comment by tiff** [comment]
That would be very nice of you.

**Comment by tiff** [comment]
Hey @david4ie, any updates?
