### ISSUE TITLE
make unittest does not work as expected

### ISSUE THREAD

**Issue by joepie91** [tiff/wysihtml5#150]
When running make unittest, the following happens:

```
[sven ~/projects/wysihtml5 16:39:35] make unittest
Bundling...
make: open: Command not found
make: *** [unittest] Error 127
```

I am using OpenSuSE 12.1 with XFCE (picked during setup, not a package group installation) and all the standard packages still installed.

I've manually opened the unit testing page to simulate the Makefile behaviour and run the unit test anyway and this worked fine, it seems the Makefile is simply breaking because of relying on an 'open' command to exist.

**Comment by tiff** [comment]
Hi @joepie91,

Unfortunately I don't have access to a machine with OpenSuSE.
Can you check whether replacing `open` with `xdg-open` or `gnome-open` works?

Thanks!

**Comment by joepie91** [comment]
Hi,

it seems both xdg-open and gnome-open work on my system, however the latter may not be available on all OpenSuSE+XFCE installs (I've manually installed a GNOME library in the past). It's probably best to just attempt open, gnome-open, and xdg-open in that order, until one is found that works.
- Sven

**Comment by tiff** [comment]
Can you check? Thx!

**Comment by joepie91** [comment]
Confirmed to work on my system now :)
