### ISSUE TITLE
Paragraphs pasted from MS Word are enclosed in <span>'s

### ISSUE THREAD

**Issue by donortega** [tiff/wysihtml5#154]
Typing paragraphs in Word, copying/pasting those into wysihtml5 results in the paragraphs wrapped in <span> tags and all appear in 1 line in the wysihtml5 field. Wrapping them in <span>'s is ok, but can we append a <br> tag to each paragraph so that each paragraph is a new line in the wysihtml5 field?

**Comment by tiff** [comment]
Hey,

I'm not able to reproduce this. I opened a new word document typed a few words + paragraphs and copied it over to the [advanced example](http://xing.github.com/wysihtml5/examples/advanced.html). The paragraphs were correctly shown as `<p>`. 
Which browser are you using? (I tested in latest Chrome and Firefox on OSX)

**Comment by tiff** [comment]
@donortega Ping! Otherwise I'm closing this.

**Comment by donortega** [comment]
Apologies for the abandonment...

As I recall, I had simply left out the advanced parser. After supplying advanced.js and doing some back-end work, all became well again.

**Comment by tiff** [comment]
Thanks!
