### ISSUE TITLE
get reference to existing editor instance

### ISSUE THREAD

**Issue by jslaybaugh** [tiff/wysihtml5#155]
I'm unable to find this documented anywhere, so I figured this was a good place to ask.  I create the editor instance using `new wysihtml5.Editor("#id")` but in this case, I don't have the luxury of sticking that reference in a global variable.  I need to be able to get to the editor object via the id of an existing element in a completely separate context (also, I'll have a variable number per page that are iterated through and created dynamically so within the context of that loop, it would be nice if I could grab that specific instance so i can call things like `editor.getValue` and `editor.setValue`.  Is there any way to find get the editor based upon element id?

**Comment by Calamari** [comment]
Global variables should be avoided, that's right.

But you can do something like this: Create the instance of the editor and store it on the element. In jQuery Syntax it could look like this:

```
var editor = new wysihtml5.Editor("#id");
editor.observe("load", function() {
  $("#id").data("editor", editor);
});
```

Then you could get it directly from the textarea field it belongs to.

**Comment by jslaybaugh** [comment]
Sorry for being dense, but how would I get it from the textarea after that?

Last night I ended up doing this (I'm using jQuery already):

```
        var editor = new wysihtml5.Editor(el.attr("id"), { // id of textarea element
            toolbar: "wysihtml5-toolbar" // id of toolbar element
        });

        $(element).data("wysihtml5", editor);
```

so then later I can just grab it from the data object on the element:

```
        var editor = el.data("wysihtml5");
```

And it seems to work in preliminary testing, but is there anything wrong with this technique or something that would make your method better?

Thanks!

**Comment by Calamari** [comment]
Well I had a copy and paste error in my last comment, but corrected it. But what you say is a good approach. But I recommend to set the data attribute only after the editor was initialized itself successfully. That's when the load event is fired. This way you can switch the method from `editor.setValue()`to `$(textarea).val()` if something went wrong
