### ISSUE TITLE
Bug: Resized image snaps back to original size

### ISSUE THREAD

**Issue by uflidd** [tiff/wysihtml5#157]
How to reproduce:

Browser: IE 9
1. Go to the Demo editor: http://xing.github.com/wysihtml5/examples/advanced.html
2. Insert a image
3. Resize image by dragging the image.
4. Switch to view Html source.
5. Switch back to see editing mode
6. Repeat step 3-5

Image is now back to orginal file size.

---

Other browsers: 

*Firefox：
Follow the same steps as above. Same bug happens
- Chrome and Safari (webkit) do not have option to resize to begin with (Someone should post a new issue for this.)

**Comment by tiff** [comment]
Haven't checked this yet in a IE9 as I'm currently on the go where I don't have access to a IE9.
