### ISSUE TITLE
does not allow embed code of any kind to be entered into the html editor

### ISSUE THREAD

**Issue by Epyon616** [tiff/wysihtml5#161]
I've tried adding various embed codes (youtube, vimeo, soundcloud etc.) and every time you paste the code in, it vanishes immediately is there a reason for this? I have also tried this on the demo site and the behaviour is the same there too, I am currently using the wyshtml5-rails gem in my project but at present neither your code or the rails gem are working as I would expect. I am sure I was able to use embed codes when I tried it out on the demo site before so has something changed to stop this?

**Comment by edwardmsmith** [comment]
When you paste, the entire contents on the editor are run through the parser, which uses whatever you've set for parser rules.  Same thing as if you did an `editor.getValue()`.

The demo using the advanced rules strips iframes: https://github.com/xing/wysihtml5/blob/master/parser_rules/advanced.js#L175

So, this is why that's happening.

You can add iframes using the editor, but when you use getValue(), they're going to be stripped.

So, if you want to allow iframes, modify your parser rules to let them pass.

**Comment by tiff** [comment]
What @edwardmsmith said (Thanks, Edward!).

**Comment by edwardmsmith** [comment]
Err, to be precise I should have said `getValue(true)` - which tells wysihtml5 to run the parser first.  `getValue()` does not run the html through the parser.

**Comment by Epyon616** [comment]
Sorry for the delay I will give this a try and see if it works for me, thanks for your help!

**Comment by jumarmundo** [comment]
Does anyone know why they allow for the option to strip iframe tags?
