### ISSUE TITLE
img src parser

### ISSUE THREAD

**Issue by p3drosola** [tiff/wysihtml5#163]
```
wysihtml5.dom.parse("<img src='/something.png'/>", {tags:{
img:{
  check_attributes: {
    src: 'src'
  }
}
}})
```

should return `<img src='/something.png'/>` if i'm not mistaken, 
but it's returning `<img>`

Basically neither the `src` or `href` are allowing relative image urls...

**Comment by tiff** [comment]
Hi. You are using the parser rules from `master` while you're using the library v0.3 which contains an old state.
Either compile master by running `make` or use the [parser_rules from v0.3](https://github.com/xing/wysihtml5/blob/9751bbd34d3c0d7e93a5873dd33ca336d61c8542/parser_rules/advanced.js).
Sorry. I know this is confusing. Working on a fix.

**Comment by p3drosola** [comment]
you mean the files in `/dist` are old?
which version should I use then? `rc1`, `rc2` ?

**Comment by p3drosola** [comment]
never mind, figured it out. Yeah, I think a warning would be handy... I'll make a pull request

**Comment by jvetter713** [comment]
Simple fix:  The src check should be changed from src to url
"img": {
            "check_attributes": {
                "width": "numbers",
                "alt": "alt",
                "src": "url",
                "height": "numbers"
            },
            "add_class": {
                "align": "align_img"
            }
        },
