### ISSUE TITLE
Non-Editable content

### ISSUE THREAD

**Issue by p3drosola** [tiff/wysihtml5#165]
Is it possible to make certain parts of the content non-editable? 

Adding `contenteditable="false"` works if you've allowed that attribute for a specific tag.

The problem with this is that `contenteditable="true"` get's applied to all the other tags of that type, and it's not stripped after editing.

Any ideas?

**Comment by Mipme** [comment]
Can't you remove the contenteditable-attribute after some kind of submit? With jQuery or htmlpurifier? Or is that not possible / feasable?

**Comment by p3drosola** [comment]
It's certainly not very clean... but yes, it's possible.

**Comment by tiff** [comment]
Try setting this style on the elements you want to make non-editable `-webkit-user-select: none;`

**Comment by tiff** [comment]
@p3drosola did the above work? I'm not planning to add any functionality to wysihtml5 concerning this.

**Comment by p3drosola** [comment]
works on chrome/webkit but I don't have my hopes up for IE. Currently using it ATM though.

**Comment by tiff** [comment]
afaik it only works with IE 10+ http://blogs.msdn.com/b/ie/archive/2012/01/11/controlling-selection-with-css-user-select.aspx :(
I'm closing this, as I don't see how wysihtml5 can fix this problem...
