### ISSUE TITLE
textarea 'disabled' attribute not affecting wysihtml5

### ISSUE THREAD

**Issue by jonagoldman** [tiff/wysihtml5#169]
I have a textarea that in some specific cases is disabled (disabled="disabled"), but wysihtml5 still allows to edit.
I need to call a specific method to disable wysihtml5?
if there is no such method, how can I manually disable it?

Thanks!

**Comment by tiff** [comment]
`editor.disable()`

I'll make sure that the attribute is correctly copied over to the editor. Thanks!

**Comment by bgerrissen** [comment]
Modifying snippet/plugin to fix disabled and readonly states:

```
function enforceInactiveStates() {
    var disabled = this.textareaElement.disabled;
    var readonly = !!this.textareaElement.getAttribute('readonly');

    if (readonly) {
        this.composer.element.setAttribute('contenteditable', false);
        this.toolbar.commandsDisabled = true;
    }

    if (disabled) {
        this.composer.disable();
        this.toolbar.commandsDisabled = true;
    }
}
editor.on( 'load', enforceInactiveStates );
```

**Comment by jayhoonova** [comment]
++ superb
