### ISSUE TITLE
Using arrow keys for navigation broken in Firefox

### ISSUE THREAD

**Issue by qrush** [tiff/wysihtml5#17]
Basically the events aren't captured by the editor, so the entire page scrolls instead.

Looks like Quora had a similar problem: http://www.quora.com/How-did-Quora-fix-the-contentEditable-bug-in-FF

**Comment by qrush** [comment]
Hm, I can't reproduce this on the advanced editor example...I wonder if something we're doing is conflicting here...

**Comment by qrush** [comment]
I can't even reproduce this now. Disregard me and my crazy rambling on this issue :)

**Comment by tiff** [comment]
No problem :) gave it a quick try and wasn't able to reproduce it either
