### ISSUE TITLE
space after anchor from createLink

### ISSUE THREAD

**Issue by lookfirst** [tiff/wysihtml5#171]
If I select some text and then use createLink to create the link, everything works fine.

If I just trying to insert a link where the cursor is, then createLink makes an anchor with a space at the end of it like so...

```
<a href="">foo </a>
```

commenting out this line in createLink::_format() fixes the issue:

```
composer.selection.insertNode(whiteSpace);
```

I suspect that you're trying to insert the space outside of the anchor, but that isn't working right.

**Comment by ashaegupta** [comment]
Thanks! I used this.

**Comment by lookfirst** [comment]
:clap:

**Comment by tiff** [comment]
Thanks for reporting. I scheduled it to be part of 0.4. This means that I'm going to work on this very soon.
