### ISSUE TITLE
Underline command not working?

### ISSUE THREAD

**Issue by jslaybaugh** [tiff/wysihtml5#173]
Check out this fiddle: http://jsfiddle.net/STGMy/

The code is the same for bold, italic, and underline, but underline doesnt work at all (tested in Chrome, Safari, Firefox).  I'm using v0.3.0 rc2 and the advanced.js parser rules from the current master branch.  According to https://github.com/xing/wysihtml5/issues/29 this should just insert a `<u></u>` tag like it does for `<b>` and `<i>` but it isn't doing anything.  Sometimes I can get it to insert some blank span tags if nothing is highlighted but no `<u>`.  The parser rules for "u" are the same as "b" and "i" so I'd think it would work.

Any ideas?

-Jorin

**Comment by tiff** [comment]
Can you try this with current master (compiled with `make`)? thanks

**Comment by jslaybaugh** [comment]
Yes, compiled the current master as of commit 9705b629af74f75b8d7f8552e372d7b7e629f37b running now at http://jsfiddle.net/jslaybaugh/STGMy/7/ and the underline functions seem to work now!

I can obviously use this build I just made, but when will a dist with this fix go live in this repo?

**Comment by tiff** [comment]
Within the next days...
