### ISSUE TITLE
Extending the toolbar -with some extra buttons

### ISSUE THREAD

**Issue by ra00f** [tiff/wysihtml5#176]
Hello,

I need to add some more buttons to the toolbar.

Basically, I need to provide the users to insert certain unicode characters for fractions - ½, ¼, ¾ etc and some other symbols for inches, degrees 

I've altered the toolbar to the GUI, but I don't know how to make the command work. Hope this would be simple as it doesn't include any HTML parsing rules. The buttons should insert the specified character, in to the iframe, when clicked.

I currently have the following code in the toolbar

&lt;li data-wysihtml5-command=&quot;insertInches&quot; title=&quot;Insert inches symbol&quot; class=&quot;command&quot;&gt;&lt;/li&gt;<br>
&lt;li data-wysihtml5-command-group=&quot;foreFrac&quot; class=&quot;fore-frac command&quot; title=&quot;Insert the fraction&quot;&gt;<br>
&lt;ul&gt;<br>
&lt;li data-wysihtml5-command=&quot;foreFrac&quot; data-wysihtml5-command-value=&quot;&frac12;&quot;&gt;&frac12;&lt;/li&gt;<br>
&lt;li data-wysihtml5-command=&quot;foreFrac&quot; data-wysihtml5-command-value=&quot;&#8531;&quot;&gt;&#8531;&lt;/li&gt;<br>
&lt;li data-wysihtml5-command=&quot;foreFrac&quot; data-wysihtml5-command-value=&quot;&#8532;&quot;&gt;&#8532;&lt;/li&gt;<br>
&lt;/ul&gt;<br>
&lt;/li&gt;

Any help would be appreciated.

Thanks.

**Comment by Mipme** [comment]
Hi ra00f,
you could try it with inserting html-code:

```
  <a data-wysihtml5-command="insertHTML" data-wysihtml5-command-value="&frac14;">1/4</a>
```

Haven't tried myself tough...

**Comment by ra00f** [comment]
Thank you so much for the reply. It's as simple as that!

```
<li data-wysihtml5-command="insertHTML" data-wysihtml5-command-value="½">½</li>
```
