### ISSUE TITLE
Strips element attributes

### ISSUE THREAD

**Issue by vendion** [tiff/wysihtml5#179]
Using wysihtml5 0.3.0 with the advance parser rules it seems to strip out element attributes.  For example using Google Code Prettify in a wysihtml5 editor it will strip out the class attribue from both the `<pre>` or `<code>` tags.

An example of such, entering the following:

``` Go
<code class="prettyprint">
package main

import "fmt"

func main() {
        fmt.Println("Hello World")
}
</code>
```

Becomes:

``` Go
<code>
package main

import "fmt"

func main() {
        fmt.Println("Hello World")
}
</code>
```

Due to this the pretty print javascript does not know to color code the syntax.

Here is a link to the [Google Code Prettify library](http://code.google.com/p/google-code-prettify/)

**Comment by NWSE-ICO** [comment]
You can add that class name to the whitelist. For the advanced.html example, you would have to add in advanced.js:

var wysihtml5ParserRules = {
    /**
     \* CSS Class white-list
     \* Following CSS classes won't be removed when parsed by the wysihtml5 HTML parser
     */
    "classes": {
       "prettyprint": 1,
      ...

Does that help?

**Comment by tiff** [comment]
@vendion Can this be closed now?

**Comment by vendion** [comment]
Sorry I haven't had time to test that out sooner, yes it can be closed.
