### ISSUE TITLE
Pasting in source view

### ISSUE THREAD

**Issue by tekin** [tiff/wysihtml5#180]
I'm interested to know if the following behaviour can be easily changed:

Currently, if I'm in the source view manually adding HTML, the parser can be over-zelous in cleaning things up. For example if I type `<img src="` and then paste in a URL, the editor clears the entire thing, I'm guessing because the parser didn't like the incomplete tag. So I guess my question is: Would disabling the parser when in source view be the answer? If so, how would I go about doing this? Cheers.

**Comment by tekin** [comment]
My current work around is to do the following to stop the parser being run in source mode: `editor.events["paste:textarea"] = [];`. Good idea/bad idea?

**Comment by tiff** [comment]
@tekin Your work around looks good to me. Anyway: I removed the parsing of the textarea value after paste.

**Comment by tekin** [comment]
Thanks @tiff. Another question, it doesn't look like the parser is run if you submit the form while still in the source view. Do you think it should be?
