### ISSUE TITLE
set_attributes & set_class not working

### ISSUE THREAD

**Issue by neojp** [tiff/wysihtml5#183]
I've tried this so many times already, I'm pretty sure I'm either doing something wrong or this feature is just broken.

To keep the code simple, I downloaded an exact copy of the current version of the files from the live example.
http://xing.github.com/wysihtml5/

Then proceeded to wrap the form fields in a `<form>` tag, added a `name` attribute to the `<textarea>` and added a submit `button`.

Once I added some links with the default `parserRules` from advanced.js I noticed that the links didn't have the attributes `rel` and `target`, just the default `href` and `title`.

``` js
"a": {
    "check_attributes": {
        "href": "url"
    },
    "set_attributes": {
        "rel": "nofollow",
        "target": "_blank"
    }
},
```

I also tried using `set_class` with one of the white listed class names and was not added.

``` js
"a": {
    "check_attributes": {
        "href": "url"
    },
    "set_attributes": {
        "rel": "nofollow",
        "target": "_blank"
    },
    "set_class": "wysiwyg-color-blue"
},
```

Can someone please help me out with this?

**Comment by tiff** [comment]
The parser is only invoked right before the content is submitted... not on runtime when the link is created. To invoke the parser you can call  `editor.parse(editor.composer.element);` right after you link has been created. Does that help?

**Comment by codescribler** [comment]
Hi Chris,

Was this supposed to be sent to me? Assuming this My binding handler may
not be the best way but it is working. Should I look into the parser to
simplify/improve my binding handler?

Danny

**Comment by tiff** [comment]
@codescribler do you have the same problem as @neojp? Which issue are u referring to?

**Comment by neojp** [comment]
@tiff Thanks, I finally understand how this works. So, all attributes are parsed on submit, and not while trying to use `editor.getValue();`

The problem we were encountering was that there is no example of how to do this on the site or on the documentation. So, I easily assumed it was broken.

We were retrieving the data using JS and sending it over AJAX, therefore I believe the submit event you guys assigned was never triggered.

I think you might want to move this functionality to `getValue()` instead, which would make more sense to me.
Feel free to close this if you don't agree with me on this one, thanks.

**Comment by tiff** [comment]
`getValue` already supports returning the content parsed. Just call `editor.getValue(true)`.
I'm planning to add a lot of documentation concerning the javascript api. Thanks!

**Comment by neojp** [comment]
Ah, excellent! `editor.getValue(true)` works perfectly. Thanks you very much.

**Comment by brainztorm** [comment]
Hi,

I have this kind of problem too but with a little difference :

when i use `javascript editor.getValue(true)` on a link "test", i get : `<a target="_blank" rel="nofollow">test</a>`

when i use  `javascript editor.getValue()`  on a link "test", i get : `<a href="www.test.com">test</a>`

... almost there ! ;) any thoughts to have the 2 simultaneously ? 

Thanks !

François. @brainztorm

PS:
I use the latest myself-compiled version from yesterday (10/10/2012) with this code:

``` javascript

       var editor = new wysihtml5.Editor(textareaid, { // id of textarea element
              toolbar:      toolbarid, // id of toolbar element
              stylesheets:  "/public/stylesheets/iframe.css",
              style:                false,
              name:  textareaid,
              parserRules:  wysihtml5ParserRules
        });

```

and stock advanced.js :

``` javascript

        "a": {
            "check_attributes": {
                "href": "href" // if you compiled master manually then change this from 'url' to 'href'
            },
            "set_attributes": {
                "rel": "nofollow",
                "target": "_blank"
            }
        },

```
