### ISSUE TITLE
Get selected image element

### ISSUE THREAD

**Issue by aykutyaman** [tiff/wysihtml5#184]
How can I select an image element created previously in order to set its attributes later. I used a custom image browser and editor.composer.commands.exec('insertHtml', url) to insert image, and I cannot access this element later.

**Comment by tiff** [comment]
Give it an id or class and target it after you've inserted it via:

``` javascript
var editor = wysihtml5.Editor({ /* ... */ });

editor.composer.commands.exec('insertHtml', '<img src="foo.gif" id="foo">');

doSomething(editor.composer.doc.getElementById("foo"));
```
