### ISSUE TITLE
Cursor disappears when inserting a list

### ISSUE THREAD

**Issue by javan** [tiff/wysihtml5#186]
Easily reproducible at http://xing.github.com/wysihtml5/examples/advanced.html in Chrome and Safari.
1. Click on the editor to give it focus
2. Click 'insertUnorderedList' or 'insertOrderedList'

The cursor is lost and the toolbar item doesn't become active until you click in the editor again.

**Comment by tiff** [comment]
Thanks! Reproducible to me. This used to work. I assume that something changed in Webkit. Will look into this asap and include it into v0.4.
