### ISSUE TITLE
Applying certain styles to lists causes the object resizer to appear in IE9

### ISSUE THREAD

**Issue by javan** [tiff/wysihtml5#19]
We have a style like this used by our editor. (Our selector is actually more generic, but the problem occurs when it's applied to UL and OLs)

``` css
body > ul {
  max-width: 508px;
  overflow: hidden;
}
```

After much debugging I've discovered that it's causing the object resizer to appear even though we have `allowObjectResizing: false` in our config.

Screenshot: http://cl.ly/0U2p3v0p1q2X0m112h3u

If I change the style to something like `color: red` the resizer goes away so it may only be related to layout-type styles.

**Comment by tiff** [comment]
Hi javan,

setting allowObjectResizing to false will trigger <code>document.execCommand("enableObjectResizing", false, false);</code>
The problem with that is that till now IE is the only browser who doesn't support that command.
Afaik it's impossible to remove the resize handles in that browser.
Therefore I implemented something for IE which prevents the default behavior for when the user is resizing an element (means the resize handles are visible but not responding).

However your problem looks a little different:
It seems that some styles (I suspect <code>overflow: hidden;</code>) make IE think that the element can be resized.

I will try to reproduce this.
Are those styles definitely the only ones that are set on the <code>&lt;ul&gt;</code>?
Is there maybe a <code>position: absolute | relative;</code> on the list?
Are you replacing the styles with <code>color: red</code> or a you adding <code>color: red</code>?

Thanks for your help!

**Comment by javan** [comment]
I just put together a bare metal example to make sure there wasn't anything else involved.

``` html
<!DOCTYPE html>
<html lang="en">
<head>
<title>test </title>
  <script src="wysihtml5-0.3.0_rc1.js" type="text/javascript"></script>
  <meta charset="utf-8">
</head>

<body>
  <div id="toolbar" style="display: none;">
    <a data-wysihtml5-command="insertUnorderedList">insertUnorderedList</a>
  </div>
  <textarea id="editor"></textarea>
  <script type="text/javascript" charset="utf-8">
    new wysihtml5.Editor("editor", { toolbar: "toolbar", stylesheets:  "stylesheet.css" })
  </script>
</body>
</html>
```

And my stylesheet just contains:

``` css
ul { overflow: hidden; }
```

Here's the result: http://cl.ly/3P1c0W2V1Y07151x1W2r

I can replace `overflow: hidden` with `width: 100px` and it causes the same issue so it feels like any style that tickles the layout causes this. I can replace that whole style with `ul { color: red; }` and the resizer goes away (and the list becomes red).

**Comment by javan** [comment]
p.s, IE #_&$^@#$_&@!!

**Comment by tiff** [comment]
Correction: my last commit could fix this issue. Still needs to be checked.

**Comment by javan** [comment]
Just checked IE9 and it doesn't look to have fixed it. Let me know if I can provide any more info. Thanks for your work!

**Comment by tiff** [comment]
I really hoped this would be fixed by making sure the iframe runs in IE9 mode.
Really felt like an old IE < 8 problem (hasLayout ...) to me.

Now this is causing me headaches.
As said it's impossible to deactivate the resize handles so I'm checking whether there are some CSS workarounds.

Is there from your point of view anything that can be done to (temporarily) bypass this problem in basecamp?

**Comment by javan** [comment]
I meant to write your earlier today. Sorry! We yanked the styles from Basecamp so we're not too concerned about this issue for now. The styles were added to avoid breaking our text doc styling if something forcefully wide was pasted in. We'll address it in a different way if it becomes a problem for us again.

**Comment by tiff** [comment]
Ok, I will keep this opened and have a closer look later.
