### ISSUE TITLE
Undo command doesn't work correctly with lists automatically created from lines.

### ISSUE THREAD

**Issue by tamaspap** [tiff/wysihtml5#191]
Reproducing the problem:
1. Open editor: http://xing.github.com/wysihtml5/examples/advanced.html
2. Type some lines (ex. one, two, three -> each word in a new line)
3. Select the lines, and create an ordered/unordered list from them
4. Execute 'undo' command (from gui or console: editor.composer.commands.exec('undo'))

The created ordered/unordered list will not change and after the list the original lines will appear.
NOTE: If using Ctrl+z from keyboard, and not the command 'undo' everything works well.

If I can help solving this issue, tell me :)

**Comment by tiff** [comment]
This is already fixed in master. Either compile master (`make`) or wait for v0.4 which should arrive in the upcoming days.

**Comment by tamaspap** [comment]
Thank you tiff! Appreciate your work!
