### ISSUE TITLE
color (span) is stripped on submit

### ISSUE THREAD

**Issue by abatko** [tiff/wysihtml5#194]
I have an editor with the following features:
- bold
- italic
- red
- ordered list
- unordered list
- link

Everything works, except **red** is stripped on submit (i.e. the span tag is stripped).

Also, if I edit the content item in the database, adding `<span class="wysiwyg-color-red">redredred</span>` manually, it renders as expected in the content view, but is stripped by the editor when I load the page with the editor.

Any idea what might be going wrong?

I'm using `0.3.0` and `simple.js`.

**Comment by tiff** [comment]
Hey. `simple.js` is the problem. It doesn't allow colors at all. Check the parser rules in `advanced.js`. It includes a list of white listed css classes.

**Comment by abatko** [comment]
Thanks for your response. I recognized that earlier, so I added `classes` to `simple.js`, but it did not make a difference.

```
var wysihtml5ParserRules = {
  "classes": {
      "wysiwyg-color-red": 1
  },
  tags: {
    strong: {},
    b:      {},
    i:      {},
    em:     {},
    br:     {},
    p:      {},
    div:    {},
    span:   {},
    ul:     {},
    ol:     {},
    li:     {},
    a:      {
      set_attributes: {
        target: "_blank",
        rel:    "nofollow"
      },
      check_attributes: {
        href:   "url" // important to avoid XSS
      }
    }
  }
};
```

As well, I have tried `advanced.js`, and again, it also did not make a difference to my span/color/red issue.

**Comment by abatko** [comment]
Could someone please still look into this even those this issue has been marked "closed"? It remains an outstanding issue on my end. Thanks.

**Comment by tiff** [comment]
I tried to reproduce this behavior with your setup.
See: http://tifftiff.de/wysihtml5-dev/examples/simple.html

Still not reproducible to me (please check by yourself). If your editor is live somewhere then share a link and I might give it a look.

**Comment by abatko** [comment]
You were right. The issue was entirely on my end. It turns out that I had not compiled my assets. I am _very_ sorry for wasting your time.
