### ISSUE TITLE
Dynamic multiple editors

### ISSUE THREAD

**Issue by patik** [tiff/wysihtml5#198]
I'm trying to use a factory method to create `n` separate editors on one page. In the HTML there are separate `<textarea>`s and toolbars for each one. 

The problem I'm running into is getting a reference to the current `wysihtml5.Editor` inside an event handler. See [this gist](https://gist.github.com/3612901) at line 18 for an example.

The issue of multiple editors was mentioned in [issue #20](https://github.com/xing/wysihtml5/issues/20) but in the given example, each editor is given its own, pre-determined JS variable (`editor_one`, `editor_two`, etc). I'm looking for a way to avoid making all of these variables manually, and allowing the easy addition of more editors on the page.

**Comment by patik** [comment]
I found a workaround. In the event handler, `this` refers to the editor instance, and you can use `this.textareaElement` to get the `<textarea>` element. From that you can of course get its `id`. So instead of a simple array of editor objects, you can keep a key/value store using the `id` as the key.

**Comment by tiff** [comment]
I wouldn't call it a workaround but rather the expected way how this is supposed to be done :)
Thanks for the documentation.
