### ISSUE TITLE
Pasting text behavior

### ISSUE THREAD

**Issue by micho** [tiff/wysihtml5#2]
Pasting text (cmd+v) on Chrome (OSX) will cause the textarea to lose focus.
Pasting text (cmd+v) on Firefox 3.6 (OSX) will cause the textarea to keep focus, but will move the cursor to the beginning of the textarea.

**Comment by javan** [comment]
I'm noticing similar, but different behavior when testing locally and here: http://tifftiff.de/wysihtml5/examples/advanced.html

Pasting on Chrome (16.0.912.63) and Firefox (8.0.1) keeps focus, but moves the cursor to the beginning.

Pasting in Safari (5.1.1 (7534.51.22)) loses focus.

**Comment by tiff** [comment]
Thanks. Will check this asap and see whether I can get something fixed for the wysihtml5 0.3.0 release.

**Comment by kagd** [comment]
Pasting in IE8 also loses focus.

**Comment by tiff** [comment]
This should be fixed in master now. Please check and feel free to reopen if you still experience issues with pasting text.
