### ISSUE TITLE
Multiple editors per page

### ISSUE THREAD

**Issue by wvl** [tiff/wysihtml5#20]
It seems multiple editors per page is broken. The second instance on the page seems to work properly, however the first does not behave correctly. For an example, see:

https://github.com/wvl/wysihtml5/blob/master/examples/multiple.html

Is this a known limitation, or is there much standing in the way of it working?

Thanks

**Comment by javan** [comment]
I'm curious about this too. I've noticed that the toolbars collide (clicking bold in one activates bold in the other). Is there a right way to have two editors on one page or is this a known limitation?

**Comment by jhollingworth** [comment]
+1 seeing the same issue

**Comment by tiff** [comment]
+1 :)
Has the highest priority on my list right now.

**Comment by terracatta** [comment]
+1 preventing me from using it in my project

**Comment by jellybob** [comment]
It appears all but the last editor share the same Wysihtml5 instance, so any changes made will actually appear in the last editor.
