### ISSUE TITLE
Text Case Styling - is there a way to do this?

### ISSUE THREAD

**Issue by Bratzilla** [tiff/wysihtml5#204]
I want to add the option to change case as editor buttons. That is, upper case, lower case, small caps and capitalize (aka title case). I have added these styles to my editor stylesheet, and am using the advanced parser. However, I cannot figure out how to implement this. Technically, this is more of a "click to add style" situation than, say, insertHTML. The idea is simple - user highlights text in editor, and, on click, the appropriate case styling is applied.

I've dug through the Rich Text Editing  commands to see if there's anything, but nothing is jumping out at me.  What do you recommend?

**Comment by Mipme** [comment]
Hey Bratzilla,

there are at least two different ways to achieve this:
1. insert a span with the appropriate class for upper case, lower case, caps etc. like other HTML code
2. or extend the editor and adding an additional editor command; see for instance code in: https://github.com/xing/wysihtml5/issues/167

Hope that helps, have a good one!

**Comment by Bratzilla** [comment]
Thanks for the response! Question: if I use this method, will it wrap the selected text within the tags?

I'll experiment in the meantime.

**Comment by Bratzilla** [comment]
The insertHTML method does work - if I wanted to create a new, formatted text block. However, what I want to do is wrap the formatting (small caps, etc.)  around the text selected within the editor.

I finally got this to work by tricking the system. I used the formatInline command, and set it to use pseudo-tags I created (kind of like my own mark-it-up language). I then set advanced.js to replace these "fake" tags with the correct spans with class attributes. 

To get the WYSIWYG instant effect (because my target user uses Word and would expect to automatically see the new formatting) I had to define these fake tags in my stylesheet. 

When I click on view source, the fake tags were replaced with the proper ones. Unfortunately, it takes another editor event to activate the advanced parser. However, because I'm using the editor in a form, on submit I can then have PHP scrub the text just to be sure all these fake tags get replaced before the information is stored in the database.

I HATE doing it like this, but I am no javascript guru, I have a project I'm trying to finish, and the current commands just don't let me add class attributes. 

If there is a better way of handling this, please feel free to let me know.

**Comment by Bratzilla** [comment]
UPDATE:  I simply hacked the core wysihtml5.js file (non-minified) and added custom commands. This is now solved. Thanks!
