### ISSUE TITLE
Safari 6 Insert Image Not Working

### ISSUE THREAD

**Issue by johnnykahalawai** [tiff/wysihtml5#207]
Hi, I just started using wysihtml5 and I'm noticing that the insert image function in advanced example does not work properly in Safari Version 6.0 (8536.25).  

After you enter the url and click OK the image shows up in the editor but when you go to view src you just see <img alt="""> and then when you go back to the WYSIWYG view it disappears.  Or when I tried embedding the editor in my own page when you submit the form the src attribute is not in there.

I also tried it in Chrome and it worked as intended.

**Comment by johnnykahalawai** [comment]
OK.  So I double checked this to be sure.  There is a difference in the parser rules for the advanced example in the package you download from the home page (which works) and in the Git repository.  The "a" check_attributes has "href":"href" when it should be "href":"url" and the same is true for img the check_attributes reads "src":"src" instead of "src":"url"

HTH

**Comment by bitinn** [comment]
ditto this, I was upgrading using latest master, the default advance ruleset breaks copy and paste (href with be null), took me sometime to figure it out.

**Comment by tiff** [comment]
Yeah I'm aware of this. The parser rules were already changed for v0.4... sorry for the confusion!
