### ISSUE TITLE
allowObjectResizing - does this actually work?

### ISSUE THREAD

**Issue by Bratzilla** [tiff/wysihtml5#208]
Sorry if this is a dumb question, but isn't allowObjectResizing supposed to allow you to resize if set to true?

I've done that with the editor, inserted an image, but nothing seems to happen.

**Comment by tiff** [comment]
I removed that config option, since Opera, Safari and Chrome don't support resizing of objects natively. However IE and Firefox do support it. Firefox had an issue. I fixed that. Thanks!
