### ISSUE TITLE
Attribute removal when pasting into the editor

### ISSUE THREAD

**Issue by emrekilinc** [tiff/wysihtml5#214]
Hello. 

I don't know if this is a bug or causing because of my code. I insert an image to the editor. then i paste some text under the image and as soon as i paste the text(html or not does not matter) the "img" tag's src attribute just vanishes. 

Any ideas?

**Comment by emrekilinc** [comment]
I'm adding elements to the editor from js. Weird thing is, i've managed to keep my classes for my elements by adding  these

``` javascript
        "embed-link": 1,
        "embed-video": 1,
        "video-thumb": 1,
        "thumbnail": 1,
        "icon": 1,
        "video-info": 1,
        "video-content": 1,
        "google-image-item": 1,
        "gallery": 1
```

to the classes. But the attributes like href and src in img and anchor tags gets removed.

**Comment by tiff** [comment]
Please check this commit and make those changes to your parser rule set. This should then allow src and href on `<img>` and `<a>`.
