### ISSUE TITLE
Attributes are removed in HTML code 

### ISSUE THREAD

**Issue by nmcmahon** [tiff/wysihtml5#216]
A number of attributes of elements are removed by WYSIHTML5. 

For example, if the folllowing code is pasted in:

``` html
<div id="my-named-div">...</div>
```

It is turned into a plain div element with no ID.

Also, I added an anchor link with a mailto address:

``` html
<a href="mailto:someone@website.com">Email me</a>
```

The entire href attribute was removed from this.

Can anyone help with this?

**Comment by tiff** [comment]
Please check the parser rules to understand how html code is parsed:
https://github.com/xing/wysihtml5/tree/master/parser_rules

Adjust them in your project to match your requirements.

**Comment by joaotnlima** [comment]
Is there a way to allow all classes without specifying them. Think it would be better to have implemented both ways. Some cases we might want to just create blacklist instead.

**Comment by sjphillips** [comment]
I was able to allow classes for div's by defining this parser rule:
"div":{ 
                    "remove": 0,
                    check_attributes: {
                        class:"alt"
                    }
                },
