### ISSUE TITLE
Consider a more permissive license

### ISSUE THREAD

**Issue by bergie** [tiff/wysihtml5#22]
wysihtml5 looks very promising! I'd love to integrate it as another editor option in [Create](http://createjs.org/). However, Create is licensed under MIT and wysihtml5 under the more strict GPL. This would prevent me from distributing the editor, and most implementors from using it.

It would be great if the editor could at least be dual-licensed.

**Comment by caniszczyk** [comment]
+1, it would be great if you used the APLv2 or a BSD flavored license

**Comment by ianlandsman** [comment]
+1, basically anything is better than GPL :)

**Comment by taylorotwell** [comment]
Yeah, this definitely needs to be under a more permissive license. Something like MIT. Basically unusable under GPL.

**Comment by ericlbarnes** [comment]
:thumbsup: Yes please anything but GPL. http://ellislab.com/blog/comments/gpl_or_not_to_gpl

**Comment by undo76** [comment]
+1 
This one is preventing me from using it.

**Comment by karlbohlmark** [comment]
+1, pretty unusable right now without a license change. Doesn't seem likely that you're planning on adding a commercial option.

If it's going to stay GPL, this should probably be clearly stated in the README to prevent people from wasting time on an unviable option.

**Comment by troygoode** [comment]
+1

**Comment by linze** [comment]
+1 This one is preventing me from using it too

**Comment by jareda** [comment]
+1

**Comment by pawel-dubiel** [comment]
+1

**Comment by jberryman** [comment]
Some of the comments above are a bit whiny for my tastes. If the author wants to consider a different license, that's great. Otherwise please respect the author's right to license his work however he chooses.

**Comment by ericlbarnes** [comment]
@jberryman I think we all do respect his choice. In fact we all like his work so much that we want to use it but can't because of the licensing.

**Comment by jberryman** [comment]
@ericbarnes I think it's fine to express that, however it's possible that the author feels strongly that you should _not_ be able to use his code in those ways that would violate the GPL, and that he chose his license after careful consideration. In that case it is rude to say, e.g. _" this definitely needs to be under a more permissive license"_ and to suggest the code is _"unusable"_ and is _"wasting peoples' time"_.

But this discussion is OT in an already questionable issue report...

Something that I think would be rather helpful in general and for the author  in considering this issue would be for commenters to detail why specifically the GPL is limiting their adoption of the code.

**Comment by ianlandsman** [comment]
Just guessing but it looks like the author may not be sure what exactly GPL implies because of the code commit comment used when the license was committed. This is a very good article that may clear up some of why GPL is very limiting.

http://ellislab.com/blog/comments/gpl_or_not_to_gpl

**Comment by karlbohlmark** [comment]
@jberryman Of course none of us can demand anything from the author in terms of license changes. It would however be great to get a confirmation that the choice of license was deliberate so we can all just move along.

As to why specifically GPL is limiting the adoption, a short answer is: you can pretty much only use this software as a part of GPL-licensed software. That is, if you're not distributing your own software under GPL you may not include this library.

People are already making mistakes and wasting their time: https://github.com/jhollingworth/bootstrap-wysihtml5 (Trying to release an apache licensed project which contains wysihtml5, which again is not possible http://www.apache.org/licenses/GPL-compatibility.html)

**Comment by barmstrong** [comment]
+1 for something more permissive

**Comment by lancefisher** [comment]
+1 for MIT or dual licensing. Dual licensing would allow this to be used in GPL projects and other projects.

**Comment by piskvorky** [comment]
My perspective: give it to me for free, no strings attached, thanks.

Your perspective: LGPL might sound more reasonable for wider adoption, or an MIT-style license. Thanks again.

For people posting links to EllisLab blog: be sure to scroll down & read the comments section there.

**Comment by ahdinosaur** [comment]
+1 LGPL

**Comment by maccman** [comment]
+1 MIT

**Comment by newzealandpaul** [comment]
+1 MIT

**Comment by stepmr** [comment]
+1 MIT

**Comment by tiff** [comment]
It's now MIT. Sorry, for the hassle this might have caused!

**Comment by newzealandpaul** [comment]
Thanks!

On Wed, Mar 21, 2012 at 8:37 PM, Christopher Blum
reply@reply.github.com
wrote:

**Comment by mvasilkov** [comment]
License trolling, in my GitHubs. Sigh.

**Comment by ianlandsman** [comment]
Awesome! thanks. I think you're going to see your work gain a lot more recognition directly due to this change. Keep it up!

**Comment by tswicegood** [comment]
@tiff Thank you!  I wanted to include this immediately in the @armstrong project when I saw it yesterday, but the license kept us from doing that.  Going with the MIT means we can include it in our platform.  Thanks for all of your hard work getting this out there -- I hope we'll be able to help out through our use in Armstrong.

**Comment by taylorotwell** [comment]
Yes thank you very much!

**Comment by lancefisher** [comment]
Yea! Thanks!

**Comment by caniszczyk** [comment]
Thanks guys!

**Comment by bergie** [comment]
Great! This might open the door for interesting collaboration between wysihtml5 and [Hallo](https://github.com/bergie/hallo). See bergie/hallo#5
