### ISSUE TITLE
documentation: useLineBreaks

### ISSUE THREAD

**Issue by zackd** [tiff/wysihtml5#222]
seems changes @ commit 9e88e5808704c93f77f8cf0123fca67dbb138e90
result in `div`s being inserted when `useLineBreaks: false` .. was expecting `p` tags!

confused! .. looked for docs ... scanned though the source..  re-read: https://github.com/xing/wysihtml5/issues/13 .. still not sure what the expected behaviour is ! 

maybe I missed something, but thought it might be helpful to ticket this (?)  

:)

**Comment by tiff** [comment]
`<p>` is expected.
can you get into detail how you managed to produce `<div>`. Thanks!

Documentation will be available as soon as I have a stable release.

**Comment by zackd** [comment]
ok thanks, I'm doing some tests atm, will get back to you :) 
- so far only thing I changed was to set `useLineBreaks: false` .. but I'll double check everything...

**Comment by zackd** [comment]
yep, my bad, `div`s were result of some caching issue with my local dev server (grails).. have to look  into that.

Anyhow, I'm happy to say after a restart, I'm getting `p` tags as expected :) 
- tested Firefox, Chrome on OS X 10.7.4 and IE9 on Win 7

**Comment by tiff** [comment]
\o/
