### ISSUE TITLE
Pasted paragraphs collectively wrapped in extra <p> tag

### ISSUE THREAD

**Issue by mikejustdoit** [tiff/wysihtml5#223]
Since using

``` javascript
useLineBreaks: false
```

To clarify, I paste something like

> Paragraph one here.
> Paragraph two here.

And get back
`<p><p>Paragraph one here.</p><p>Paragraph two here.</p></p>`

If this is a bug I'd be more than happy to try to fix it, but any suggestions of where to begin would be appreciated.

**Comment by tiff** [comment]
I will look asap into this. Thanks very much for testing it!

**Comment by tomtaylor** [comment]
I've had a go at fixing this, but I don't know the code well enough to know exactly where to adjust the behaviour. I believe it's due to there being a root `<p>` tag at the text cursor, before paste, so everything goes inside it.

**Comment by tiff** [comment]
Hi @tomtaylor,

I was only able to reproduce this in Chrome + Safari and I think I found a fix.
Please compile `master` and check. Feel free to reopen if this still doesn't behave as expected.

Thanks!

**Comment by dhoulb** [comment]
I just hit the same issue (in Chrome, with `useLineBreaks = false` and `<p>` in the parser rules whitelist).

Can confirm that _b0c281b_ has fixed it :D Thanks!

**Comment by tomtaylor** [comment]
Thanks a lot, this seems to work for us!
