### ISSUE TITLE
How to chage the color:#000

### ISSUE THREAD

**Issue by karthikeyanar** [tiff/wysihtml5#224]
How to change

`<span class="wysiwyg-color-red">test</span>`

to 

`<span style="color:red">test</span>`

**Comment by tiff** [comment]
I'm closing this, since the goal of wysihtml5 is to not produce inline styles like `color: red`. wysihtml5 was never meant for such cases. You might wanna try a different editor or rethink your concept of rich text editing. Sorry :)
