### ISSUE TITLE
Remove html formating form pasted text

### ISSUE THREAD

**Issue by ijafri** [tiff/wysihtml5#227]
Trying hard to figure how to remove html formating from the text which is pasted into textarea. As soon as user posts the text, the html formating is removed automatically.

**Comment by tiff** [comment]
What do you mean by "remove html formatting"? You can adjust the parser rules to match your preferences. They ensure that your html gets transformed into what you expect.

**Comment by tiff** [comment]
Can this be closed, @sifarat?
