### ISSUE TITLE
"allowObjectResizing:  false" is ignored by IE9

### ISSUE THREAD

**Issue by sgrosse** [tiff/wysihtml5#243]
Hi,

it seems that "allowObjectResizing:  false" is ignored by IE9. I just took the advanced example from the downloded folder an added this config option. Firefox behaves correct but IE 9 seems to completely ignore this Option and stil provides resizing of images. IE8 is still showing the resize-anchors on the image but at least you cannot resize them anymore.

Thanks for your Support.
- Stefan

**Comment by tiff** [comment]
allowObjectResizing will not be supported by wysihtml5 anymore. It's already removed from the current code base. Due to the fact that it's not (or hardly) possible to disable it. Sorry! :)

**Comment by nicoburns** [comment]
I believe returning false io the "oncontrolselect" event stops resize handles from appearing.

**Comment by tiff** [comment]
Thanks @nicoburns. But it's just not working with IE9+ ...
