### ISSUE TITLE
How to insert multiple images into the textarea?

### ISSUE THREAD

**Issue by tim-peterson** [tiff/wysihtml5#244]
I can insert single images no problem by plugged their url's into the following input element's value: `<input data-wysihtml5-dialog-field="src" value="">` 

However, I can't figure out how to insert multiple images at the same time, thoughts?

**Comment by tiff** [comment]
You have to do this programmatically yourself. There are several ways to insert dom:

``` javascript
var fragment = document.createDocumentFragment();
var image1 = document.createElement("img");
image1.src = "foo.jpg";
var image2 = document.createElement("img");
image2.src = "bar.jpg";
fragment.appendChild(image1);
fragment.appendChild(image2);
editor.selection.insertNode(fragment);
```

or 

``` javascript
editor.commands.exec("insertHTML", "<img src='foo.jpg'><img src='bar.jpg'>";
```

Hope this helps.

**Comment by tim-peterson** [comment]
@tiff hmm, `editor.commands` and `editor.selection` are both giving me the following error:  "Cant call method exec/insertNode of undefined". 

This is the javascript causing the error that i'm typing into the console on your http://xing.github.com/wysihtml5/ page or on my website:
`editor.commands.exec("insertHTML", '<img src="https://s3.amazonaws.com/onarbor-media/uploads/12373/purchases/1/40Screen_Shot_2012-10-26_at_9.52_.13_PM_.png">');`

thoughts?

**Comment by gianluca-sabena** [comment]
Hi, the editor take some times to load, probably you need to wait for the load event

``` javascript

editorText = new wysihtml5.Editor("wysihtml5-text", { 
      toolbar: "wysihtml5-toolbar-text", 
      parserRules: wysihtml5ParserRules, 
      stylesheets: ['/pub/lib/wysihtml5/style.css','/pub/css/spacelab.css']
    }).on('load', function(){ 
        this.focus()
        this.composer.commands.exec("formatBlock", "p");
      })

```

**Comment by tim-peterson** [comment]
@intertesto thanks, that worked!  Having `composer` is key.  So  `this.composer.commands.exec("formatBlock", "p")` instead of  `this.commands.exec("formatBlock", "p")` as @tiff suggested.

Also, the textarea requires `focus`  for one to add elements via `editor.composer.selection.insertNode(fragment)`.  So for anyone who reads this, make sure to put cursor in textarea before trying to add elements. This seems sub-optimal from a UI/UX perspective but hopefully knowing to test this will be helpful to others.
