### ISSUE TITLE
Editor height is not correctly derived if textarea has "height: auto;" set to it (since commit: 78cbb8)

### ISSUE THREAD

**Issue by Calamari** [tiff/wysihtml5#246]
The following commit introduced a bug:
https://github.com/xing/wysihtml5/commit/78cbb84c6d68f7d55eb2df87646e930ed5e789ba

Before that, editor has had the same height as the responding textareas which has the css style "height: auto;". After that, the editor got a different height, then the textarea.

**Comment by tiff** [comment]
Hi @Calamari Has the affected textarea a css height (if so, which unit?) or is the height all defined by the `rows` attribute?

**Comment by tiff** [comment]
Can you try again with the current `master`(you have to compile it via `make` first).
I think I fixed this with 6072be873dfc272742245616caea41cfb9b8bfdf

**Comment by Calamari** [comment]
looks good in the new version. The height was auto in css and all derived from rows attribute
