### ISSUE TITLE
Starting a new paragraph after a list

### ISSUE THREAD

**Issue by lmclaney** [tiff/wysihtml5#249]
When starting a new paragraph after a list (both ordered and unordered lists) the text is not wrapped in paragraph tags.

**Comment by tiff** [comment]
Which version of wysihtml5 are you using? 0.3 or the compiled `master`?

**Comment by tiff** [comment]
@lmclaney if you still want me to help you then please check the comment above and reply. Thanks very much!

**Comment by lmclaney** [comment]
Sorry, I've just got back from holiday so I missed your response. I was using 0.3.0. 

You can replicate it on the main WYSIHTML5 website in both the 'Features' and 'Browser Support' sections. If you try to start a new paragraph after the list the text isn't automatically wrapped in paragraph tags as you would expect.

Cheers!

**Comment by tiff** [comment]
No problem, @lmclaney.
wysihtml5 is by default avoiding `<p>` and instead creates `<br>`
If you change to wysihtml5 0.4.0pre you can set the option `useLineBreaks` to `false` which then will create `<p>` whenever possible (also after leaving a `<ul>` or `<ol>`). Please note that 0.4.0pre is really just a pre-release and not considered stable.

Thanks!

**Comment by lmclaney** [comment]
Thanks, that's great!
