### ISSUE TITLE
Relative paths in href

### ISSUE THREAD

**Issue by aaronshaf** [tiff/wysihtml5#25]
Setting "check_attributes" to "url" precludes relative paths.

**Comment by tiff** [comment]
Hey @aaronshaf,

The editor intentionally only takes absolute urls for two reasons:

**1. Security**
It's much harder to separate a relative url from a possible xss attempt.

**2. Copy & Paste Content**
Some browsers (IE 8+9, Firefox < 12) don't turn relative urls into absolute urls when copying content from one page to another.
Let's say someone copies content including an image (/relative/path.jpg) from some-website.com into your editor.
The browser would then fire a request to your-website.com/relative/path.jpg and cause a 404 or some other unwanted behavior.

Tell me if you have any thoughts/ideas on this.

Thanks!

**Comment by tiff** [comment]
Check 4a153a832f19733c2b1a6f5c24ae2266e5b67569 and 54959a7e0c16382e390f20a9775e91abab9316fc
