### ISSUE TITLE
Why is "foreColor" called "foreColor" when it can be user to insert any extra class?

### ISSUE THREAD

**Issue by seanhinton** [tiff/wysihtml5#250]
This isn't an issue exactly but it feels like "foreColor" has the wrong name because it can be used to add any class to some inline text irrelevant of color.

So could use foreColor to change the font family of some text and that's got nothing to do with color.

**Comment by tiff** [comment]
It's not entirely true that foreColor can be used to insert any class: The given string will always be prefixed with "wysiwyg-color-".
Consider it convention.

If you want to give your selection a specific class then rather do this:

``` javascript
wysihtml5.commands.formatInline.state(composer, command, "span", "your-class");
```
