### ISSUE TITLE
focus the editor via javascript

### ISSUE THREAD

**Issue by stmichael** [tiff/wysihtml5#256]
I'd like to set the focus to the wysi editor via javascript. I already saw that in issue #213 somebody found a solution to this problem. Unfortunately that didn't work for me.

I also tried triggering the focus event on various elements in the wysi editor object but I couldn't find the right one. Among them the following:

``` javascript
editor.composer.element.focus()
editor.fire('focus')
editor.fire('focus:textarea')
editor.fire('focus:composer')
```

Is there any official way of achieving that?

**Comment by tiff** [comment]
`editor.composer.element.focus()` should work.
Go [here](http://xing.github.com/wysihtml5/examples/simple.html), open firebug or chrome developer tools and execute it. Works for me.

However best way would be to do `editor.focus()` (which would even work if the `<textarea>`is currently visible).

If you wanna go the HTML5 way set the autofocus attribute:
`<textarea autofocus></textarea>`

**Comment by stmichael** [comment]
Ok, I see that the focus event is triggered. But shouldn't I be able to see the cursor inside the editor when the focus event has been triggered?

**Comment by tiff** [comment]
Yes you should! I assume you are using firebug to test this. Can you please execute this on the example page and then immediately close firebug.

``` javascript
setTimeout(function() { editor.focus(); }, 2000);
```

Firebug prevents you from focusing elements on the page.

**Comment by stmichael** [comment]
I'm using Chrome but your tip helped my nonetheless.

I have the following use case: I submit a form which has a wysihtml5 editor. The data I submit isn't valid since the editor must have some content. So I render the form again but this time the editor is red bordered and since the editor is the first field that didn't pass data validation it has to be focused. I have a javascript file in which the editor gets the focus on document ready.

If I call focus on the editor as usual, I don't see the cursor. If I use setTimeout like you said above, the magic works! The cursor is blinking inside the editor.

Could this be a timing problem? I confirmed that the wysi editor is initialized before the focus will be set. Do you have any idea?

**Comment by tiff** [comment]
The initialization happens asynchronously.
You might be able to avoid the timeout by doing this:

``` javascript
editor.on("load", function() {
  editor.focus();
});
```

**Comment by stmichael** [comment]
Hmmm... this doesn't solve the issue. The cursor doesn't show up. I really couldn't get any more debug information about it.

Do you have any other ideas on how solve or debug it? `setTimeout` works but this is more of a workaround than a fix.

**Comment by tiff** [comment]
Sorry I can just assume: Maybe the editor is not visible (because its container is somehow hidden at that moment) and therefore the focus doesn't work or maybe some other element is stealing the focus from it...

It really seems to be something in the context of the editor not the editor itself... (correct me if I'm wrong)

**Comment by tim-peterson** [comment]
I got the textarea to focus using `editor.composer.element.focus();`, but the cursor annoyingly goes the beginning of the textarea even when text exists in the textarea. I'd like instead for the cursor to `focus` **after** all the text rather than at the beginning of textarea.

I tried to adapt this [Stackoverflow thread](http://stackoverflow.com/questions/6003300/how-to-place-cursor-at-end-of-text-in-textarea-when-tabbed-into) but the whole iframe/textarea issue has me confused.  thoughts?

**Comment by OpakAlex** [comment]
Hi @tim-peterson , this is working example(cursor to focus after all the text rather)
coffeescript code:

```
@initEditor = (options={}) ->
   $('.do_wysihtml5').each ->
     $el = $(this)
     return if $el.hasClass('wysihtml5_done')
     window.editor = $el.wysihtml5(options).data('wysihtml5').editor
     $el.addClass('wysihtml5_done')

Then works with:

window.initEditor(@options())
setTimeout( ->
  window.editor.focus(true)
 , 500)
```

**Comment by digitaldevelopmentrevolution** [comment]
$('#CommentTextArea').data("wysihtml5").editor.focus();
