### ISSUE TITLE
Doesnot work in modal popup in ASP.NET MVC 4

### ISSUE THREAD

**Issue by nahidinfo** [tiff/wysihtml5#257]
Hello,
I am working on a project ASP.NET MVC 4 , knockoutjs and twitter Bootstrap . I am trying to use  wysihtml5 text editor into twitter bootstrap Modal. It doesn't work in modal popup. 

Thanks 
Nahid

**Comment by balexandre** [comment]
Hi nahidinfo,

Please [forward to this project](http://jhollingworth.github.com/bootstrap-wysihtml5/) where Bootstrap is paired with wysihtml5 project

**Comment by nahidinfo** [comment]
Hi,
Problem was Model binding. Its works now.

Thanks
