### ISSUE TITLE
Removes pre-filled textarea of HTML

### ISSUE THREAD

**Issue by danharper** [tiff/wysihtml5#26]
Does this plugin not support editing a textarea pre-populated with HTML?

eg:

``` html
<textarea id="report_front">This is <b>bold</b>...</textarea>
```

``` js
new wysihtml5.Editor('report_front')
```

The textarea and the wysihtml5 iframe now both display:

> This is bold...

instead of

> This is **bold**...

**Comment by wvl** [comment]
You need to pass in the parser rules that match the tags you expect to see and allow. The only tags allowed by default are (br, span, div, and p). See the simple example for a set of parser rules.

**Comment by danharper** [comment]
Ah, of course! Thank you :)

**Comment by tiff** [comment]
Thanks @wvl for pointing this out! :)
I'll write a better guide on how to implement and use the editor.
