### ISSUE TITLE
Remove link

### ISSUE THREAD

**Issue by Mangatt** [tiff/wysihtml5#261]
Hello,
is there a way how to remove link from text? Ideally with simple click or with removing url in dialog - it should be similar functionality like TinyMCE have when you click the broken chain button.

**Comment by Mangatt** [comment]
For further clarification - I'm looking for command opposite for "createLink", I need a way to programmatically remove link from text.

**Comment by Mipme** [comment]
hey,

simply select the linked text and press link button again. removes link. not really obvious tough...

Am 06.11.2012 um 18:32 schrieb Mangatt notifications@github.com:

**Comment by Mangatt** [comment]
Yeah, I figured that from source code, but my second post is still unanswered - how do I programmatically remove link when I use wysihtml5 commands.

**Comment by jmalonzo** [comment]
@Mangatt Just call createLink on an existing link programmatically - https://github.com/xing/wysihtml5/wiki/Supported-Commands#wiki-createLink.

**Comment by tiff** [comment]
Right, as @jmalonzo and @Mipme already stated you have to call createLink again (most commands toggle).
You could also do `editor.composer.commands.exec("unlink")`

**Comment by spsaucier** [comment]
To prevent links from being pasted into your editor, you can initialise it with 

``` javascript
{
    autoLink: false,
    parserRules: { 
        tags: { 
            a: {"remove": 1}
        },
    }
}
```
