### ISSUE TITLE
Chrome doesn't load stylesheets when wysihtml-code-snippet is loaded dynamically

### ISSUE THREAD

**Issue by phillipoertel** [tiff/wysihtml5#262]
Webkit-based browsers fail to load a stylesheet given as option to wysihtml5.Editor in some cases.

Here's our code:

``` javascript
var editor = new wysihtml5.Editor("wysihtml5-textarea", {
        toolbar: "wysihtml5-toolbar",
        parserRules: wysihtml5ParserRules,
        style: false,
        stylesheets: ['/assets/textile_preview.css']
});
```

The DOM fragment with the above JS is loaded via AJAX and then inserted into the DOM. We suspect this _may_ cause is the problem.

Some observations:
- wysihtml correctly triggers the load of the stylesheet, but the Chrome web inspector shows the request as canceled. The response body is empty, and the iframe isn't styled. 
- the server-side log shows a successful GET request for the file.
- this happens with every CSS file, even with an empty one.
- using the Chrome debugger we can see that Chrome stops/fails when parsing the response headers. At first we thought our Rails app sends a strange header. But this happens in our staging and production environments as well, where the static CSS file is served by Apache.

I'm testing on OS X with current Chrome (23.0.1271.64).
Safari behaves the same, so it seems to be a Webkit problem. It works in Firefox.

Any ideas? Have you heard of this before? Any help would be appreciated.

**Comment by phillipoertel** [comment]
I debugged the response headers on the CSS file ... they are the same, no matter if I load the CSS file in the browser regularly (which works) or when it is loaded through JS/wysihtml.

**Comment by tiff** [comment]
Wazzaaa @phillipoertel :o)

thanks for the detailled description.
No I haven't heard of this problem before. I'll try to reproduce this and come back at you. In the meantime you can workaround this by inserting the stylesheet dynamically yourself (untested):

``` javascript
editor.on("load", function() {
  if (!editor.isCompatible()) {
    return;
  }

  var doc =  editor.composer.sandbox.getDocument();
  var link = doc.createElement("link");
  link.href = "stylesheet.css";
  link.rel = "stylesheet";
  doc.querySelector("head").appendChild(link);
});
```

**Comment by tiff** [comment]
Also, if you happen to use my workaround above, can you please provide feedback whether that fixed the problem...

**Comment by tiff** [comment]
Possibly related to #15

**Comment by tiff** [comment]
Dammit, I'm not able to reproduce this. However the referenced issue above totally backs up your problem. Seems that webkit re-renders the iframe under certain circumstances.
It would be very helpful if you could spend a little time to build a minimal demo. (www.jsfiddle.net)

Also some more informations would help me:
Which version are you using? 0.3.0?
Which library do you use to dynamically insert the HTML?

Thanks in advance.

Happy weekend.

**Comment by phillipoertel** [comment]
Hi @tiff thanks for looking into this so quickly!

I'll try to build a working "not working" demo and get back to you. Will be my first endeavour on jsfiddle :-)

Issue #15 looks mildly related, however the editor itself works as expected when we load it by AJAX, just the stylesheet isn't applied.

Greets to Hamburg,
Phillip

**Comment by phillipoertel** [comment]
The workaround works nicely and already went live, thanks!
I just tried building an isolated case but can't reproduce the problem easily ... I'll get back to you.

**Comment by phillipoertel** [comment]
Oh, we're using 0.3.0 and jQuery 1.7.2.

**Comment by phillipoertel** [comment]
Hi Christopher,

I wasn't able to create a minimal demo of the bug -- when loading the JS snippet through AJAX it works as expected. So it's probably something else in our production app that I can only find with further effort. The workaround you provided is good enough for us for the moment, hoewever.
If you would like to investigate this further and track down the bug, I'll gladly give you a look at the production code/app, contact me on skype in that case!

Thanks,
Phillip

**Comment by tiff** [comment]
Thanks for trying! Feel free to re-open if the problem reoccurs and is reproducible in a demo.

**Comment by phillipoertel** [comment]
Will do.

Phillip

---

Am 12.11.2012 um 20:27 schrieb Christopher Blum:

**Comment by rivsc** [comment]
@tiff Thanks for workaround !

Same problem on firefox.
