### ISSUE TITLE
Uncaught exception when trying to insert list

### ISSUE THREAD

**Issue by Mangatt** [tiff/wysihtml5#263]
Hello,
when I try insert ordered or unordered list in Opera 12.1 I get uncaught exception:

Unknown thread
Uncaught exception: TypeError: Cannot convert 'tempElement' to object
Error thrown at line 7588, column 8 in <anonymous function: exec>(composer, command) in http://xing.github.com/wysihtml5/dist/wysihtml5-0.3.0.js:

I've seen this behavior only in Opera, other browsers seem fine.

**Comment by Mangatt** [comment]
Can be seen in http://xing.github.com/wysihtml5/examples/advanced.html

**Comment by tiff** [comment]
Thanks. Has already been fixed in 0.4.0pre.
