### ISSUE TITLE
Add a config option to disable the sanitizer

### ISSUE THREAD

**Issue by jmalonzo** [tiff/wysihtml5#285]
There are use cases where the parser/sanitizer doesn't add anything and just gets in the way (e.g., non-public sites where customising the parser rules for every possible attribute just doesn't make sense). I think it would be nice if there's an option in the editor to disable this, and just leave the markup as-is.

I'd be happy to help with this effort, but just wondering if you have any thoughts on this?

Cheers.

**Comment by jbritten** [comment]
Any reason why you closed this request so soon after opening it?  I'd actually love to see this feature as well.

Cheers,
Justin

**Comment by jmalonzo** [comment]
I closed it because you can do this by having an identity function assigned
to the parser config param.
