### ISSUE TITLE
I'm made "html code "... but change html code ..

### ISSUE THREAD

**Issue by baejina** [tiff/wysihtml5#289]
I'm made "html code ..."

before save ( iframe inside)
<img src="http://blogfiles.naver.net/20121205_97/wlsk1103_1354702932414A248B_GIF/%B5%BF%BF%B5%BB%F3%C4%DA%B5%E5_%C0%FA%C0%E5%C0%FC.gif">

after save (db)
<img src="http://postfiles6.naver.net/20121205_245/wlsk1103_1354703023586BJ6s3_GIF/test2.gif?type=w3">

return code change...
why??? ...

**Comment by r043v** [comment]
how do you made your save ?

does all that you use is in the parser white list ?

**Comment by baejina** [comment]
No, not at all. ㅜ,ㅜ help me~ 

Put inside the iframe 'before save html code" 

does not use a parser. no sanitize

**Comment by r043v** [comment]
there is an automatic parser inside wysihtml5, check file parser_rules/advanced.js and add your need inside

``` js
 "img": {
            "check_attributes": {
                "width": "numbers",
                "alt": "alt",
                "src": "url",
                "height": "numbers"
            },
            "add_class": {
                "align": "align_img"
            }
        }
```

``` js
var wysihtml5ParserRules = {
    /**
     * CSS Class white-list
     * Following CSS classes won't be removed when parsed by the wysihtml5 HTML parser
     */
    "classes": {
        "wysiwyg-clear-both": 1,
        "wysiwyg-clear-left": 1,
        "wysiwyg-clear-right": 1,
        "wysiwyg-color-aqua": 1
```

**Comment by baejina** [comment]
Oh! So try to add  ^_____________^ you Thumbs! 

sorry... style value  how value?

https://github.com/xing/wysihtml5/issues/212 <------------ here~ ^^ have a good time~

################################################################
Solution !

 dist/wysihtml5-0.3.0.js
  // ------------ attribute checks ------------ \

```
allow: (function() {
  return function(rv) {
    return rv;
  }
})(),
```

/parser_rules $ vi advanced.js
        "img": {
            "check_attributes": {
                "longdesc": "allow",
                "id": "allow",
                "width": "numbers",
                "alt": "alt",
                "src": "url",
                "height": "numbers",
                "style": "allow",
                "class": "allow"
            },

```
        }
```

:: allow method add! ^_ ^ thank you 
################################################################

**Comment by r043v** [comment]
nice :)
