### ISSUE TITLE
Any Examples of Underlined Text?

### ISSUE THREAD

**Issue by buzzedword** [tiff/wysihtml5#29]
Trying to output an underline control, can't seem to get it down. Any examples?

**Comment by Neener54** [comment]
< a data-wysihtml5-command="underline" title="CTRL+U" class="btn" >U< /a >

.wysiwyg-text-decoration-underline {
  text-decoration: underline;
}
 for the css

**Comment by buzzedword** [comment]
ah! jesus, that's simple. Thank you!

**Comment by tiff** [comment]
Btw this has now changed to generate <u> tags since they are still perfectly valid according to the current HTML5 spec.
Doc for this command: https://github.com/xing/wysihtml5/wiki/Supported-Commands#wiki-underline
