### ISSUE TITLE
When inserting image through url can i resize the image to my needs?

### ISSUE THREAD

**Issue by abby90** [tiff/wysihtml5#290]
when i try to insert a image into my textarea using insert image option, the height and width of the image gets saved in its original problem, but i want them to be in a fixed height and width lets say 300 by 300 .

In a nutshell when inserting images, i want to be converted or inserted with height and width having 300 by 300 constant value ? is this possible ?

**Comment by zrod** [comment]
There are a few ways to accomplish that:
- Setting the dimensions for the img tag in parserRules;
- Defining a custom css class for images and then set the dimensions in that class (don't forget to reference the css through "stylesheets" option);
- Extend / customize insertImage command, ref: https://github.com/xing/wysihtml5/blob/master/src/commands/insertImage.js

**Comment by tiff** [comment]
Thanks @zrod! I'm closing this now.
