### ISSUE TITLE
Link Description

### ISSUE THREAD

**Issue by DizzleLizzle** [tiff/wysihtml5#294]
Is there an easy way to allow the users to provide display text for a link they are entering?  For example, they could enter "http://www.google.com" in the text field for the link, and enter "Google!" in a text field for the display text, and the editor would generate this html 

<a href="http://www.google.com" rel="nofollow">Google!</a>

I understand this may cause security issues, but I'm sure this has already been implemented by someone and I don't want to reinvent the wheel.  Thanks.

**Comment by jmalonzo** [comment]
@DizzleLizzle just implement your own dialog with display text and link input fields.

**Comment by DizzleLizzle** [comment]
Is there an easier way to do it than having to modify the source wysihtml5 javascript file?

**Comment by jmalonzo** [comment]
You don't have to modify the source. Just create a separate command (wysihtml5.commands.linkifyWithDescription, etc..) that will allow you to show a dialog and will allow you to enter description, etc... There's a bunch of examples in src/commands for you to start with. You can probably even use the createLink command (i.e., call it via JS) for this.

**Comment by DizzleLizzle** [comment]
Easy enough.  Thanks.  Here is the HTML in case anyone else needs it.  It didn't even need a separate command.  I was able to reuse createLink.  Thanks for the help.

```
<div data-wysihtml5-dialog="createLink">
    <label>
         URL: <input data-wysihtml5-dialog-field="href" value="" class="text">
    </label>
    <label>
         Display: <input data-wysihtml5-dialog-field="text" value="" class="text">
    </label>
    <a data-wysihtml5-dialog-action="save">OK</a> <a data-wysihtml5-dialog-action="cancel">Cancel</a>
</div>  
```

**Comment by tiff** [comment]
I'm closing this. Thanks @jmalonzo for the support!
