### ISSUE TITLE
please do a smallest edition

### ISSUE THREAD

**Issue by r043v** [tiff/wysihtml5#296]
it will be awesome if some part will be optionnal like toolbar, white list parser, view flip & textarea support ...

i write a small [jquery plugin](https://github.com/r043v/jQuery.scribe) who use wysihtml5 and i not use or overide some of these feature

can a core only edition is possible ?

**Comment by tiff** [comment]
That is not a "smallest edition". :smile: 
Sorry to disappoint you but I don't think that's gonna happen (at least I don't want to work on such a thing).
wysihtml5 is already very lightweight compared to other editors like TinyMCE.
