### ISSUE TITLE
Insert html through custom control

### ISSUE THREAD

**Issue by Neener54** [tiff/wysihtml5#30]
I'm probably just missing something simple, but is there a way to insert elements through javascript?  We have a custom system for handling images and I need to find some way to hook into that.

**Comment by Neener54** [comment]
I just went around it and accessed the contents using plain old javascript.  Would be nice to have an updateComposer method and an updateTextarea method though.

**Comment by adampatterson** [comment]
How did you go about that?

I want to make a media manager and it would insert html as well.

Thanks!
