### ISSUE TITLE
wysihtml5 applying :focus styling causes onfocus to fire

### ISSUE THREAD

**Issue by jonchay** [tiff/wysihtml5#302]
Hi there, first and foremost I love this wysiwyg editor thank you for your hard work!

I'm currently having an issue when I've binded an onfocus event to the textareaElement, but the function is being fired when wysihtml5 is being initialized. I have followed up the code and this line seems to be the one firing the event instead of the user:

https://github.com/xing/wysihtml5/blob/master/src/views/composer.style.js#L85

This then causes the textareas' onfocus to always fire on pageload.

This is an example of a textarea I'm initializing on:

``` html
<textarea class="text required wysiwyg" cols="40" id="test" name="answer[body]" onfocus="console.log('Focusing...');" rows="20">
</textarea>
```

Are there any alternatives? We're conditionally intializing wysithml5 depending on the user browser, and hence we can't rely on the focus event provided by wysihtml5. Eventhough it applies to both composer and textarea. 

Thanks in advance for any help you could provide!

**Comment by markokeeffe** [comment]
I'm experiencing problems with the same behaviour.

I have pre-loaded javascript that validates the textarea on blur. When wysiHTML5 initialises, it focuses and then blurs the textarea, firing the validation, causing a 'XYZ cannot be blank' error.

Is there any reason why the textarea element is given focus and then blurred when the wysiHTML5 editor is initialised?

**Comment by jonchay** [comment]
Hi Mark, when I had this issue a while ago I looked into wysihtml5 code and it appears that the reason why they focuses the textarea element is to copy any stylings of it <code>textarea:focus</code> onto the wysihtml5 iframe. They do so to make the iframe consistently styled with any textarea styling you may have.

For your problem, would you need to focus onto the textarea to check if it's blank? I would think something like this would work: <code>if ($('textarea').val() == "")</code>
