### ISSUE TITLE
Uncaught Error: NOT_SUPPORTED_ERR: DOM Exception 9

### ISSUE THREAD

**Issue by Neener54** [tiff/wysihtml5#31]
I'm receiving this error when I attempt to call: wysihtml5.selection.insertHTML("<p>foobar</p>"); 
I'm not even sure if this is how you would call this method, although it appeared to be working when I called the insertImage version.  

If I find time I'll look into this later and see if I can help you solve it.  But it's Friday and I'm going home. ha ha.

line 2345 RC1 0.3

// Test for existence of createContextualFragment and delegate to it if it exists
            if (api.util.isHostMethod(range, "createContextualFragment")) {
                rangeProto.createContextualFragment = function(fragmentStr) {
                    return this.nativeRange.createContextualFragment(fragmentStr);
                };
            }

**Comment by tiff** [comment]
First of all upgrade to wysihtml5 RC 2 and then try:
`yourEditor.composer.commands.exec("insertHTML", "foobar");`
If you're still receiving that error then make sure that the editor has focus before inserting HTML:
`yourEditor.focus();``

(yourEditor should be the instance of your editor)

Does that help?

**Comment by Neener54** [comment]
Yes thanks this mostly fixed my problem, works really well until I have multiple editors on one page.  So now all I have to do is come up with a method of determining which editor I'm in and updating accordingly.   Thanks!
