### ISSUE TITLE
Single Toolbar with many editors

### ISSUE THREAD

**Issue by nevf** [tiff/wysihtml5#32]
I have a page _(actually an app)_ that will have many editable textareas and I just want a single toolbar for these, probably at the top of the page or floating. I've worked out how I can create a Toolbar dynamically using:

```
var toolbar = new wysihtml5.toolbar.Toolbar( editor, document.getElementById("wysihtml5-toolbar") ); 
```

but so far I haven't worked out how I can get this to only work with the textarea that has focus.

-Neville

**Comment by Neener54** [comment]
I declared my toolbar in the config of the editor and haven't had any problems using the toolbar for multiple editors.  That being said I am using handlebars to create templates of the toolbars so the id is unique for each of them.  We use handlebars a lot here though so adding in the template was pretty easy.  

If you need immediate results I'd highly recommend trying out handlebars.

Here's a Gist of what I'm doing https://gist.github.com/2285181

I'm not 100% done, but as long as you aren't doing anything crazy (which is what I'm doing), this works pretty well.

Keep in mind the .hbs extension is used in our rails handler for handlebars (we pre-compile our templates on the server so we don't have to have full library on the client side, not necessary but it's nice if you're trying to optimize bandwidth).

**Comment by nevf** [comment]
@Neener54 - Thanks, I'll have a close look at your Gist. I assume you only have one Toolbar that is shared across all editor instances. And that toolbar is somehow set active for the instance that has focus?

I'm using my own simple and specific templating code, so handlebars isn't a viable option, nor should it be necessary.

-Neville

**Comment by tiff** [comment]
Hey @nevf, can this be closed?

**Comment by nevf** [comment]
@tiff I've only had a quick look at @Neener54 gist and really don't know how useful it is. 

I've not had time to actually try anything out as yet and have been hoping that native support for this capability would be included in wysihtml5, as it seems like a very useful option that other folks would want to use.
