### ISSUE TITLE
support for latest version of jQuery

### ISSUE THREAD

**Issue by rolandjitsu** [tiff/wysihtml5#342]
I'm using the latest version of jQuery and <code>$.browser.msie</code> seems not to be supported anymore, because I get an error each time I open the editor

**Comment by jmalonzo** [comment]
I don't think jQuery is a dependency of wysi - are you sure it's wysi's fault?

**Comment by rolandjitsu** [comment]
When I went back to 1.8.3 I don't have the error. Only when I used 1.9.1. It might be that they stripped <code>$.browser.msie</code> out of that version as they were saying that after version 2 they will no longer support old browsers.

**Comment by r043v** [comment]
come see source https://github.com/xing/wysihtml5/blob/master/dist/wysihtml5-0.4.0pre.js

ctrl F to find msie or $

not found

check source file linked to your error, it cannot be wysihtml5

and use jquery migrate plugin to give back old deprecated functions
https://github.com/jquery/jquery-migrate/#readme

**Comment by rolandjitsu** [comment]
It could be bootstrap wysihtml5 that does that. I'll check that then :)
