### ISSUE TITLE
Is there a good way to get a keydown event?

### ISSUE THREAD

**Issue by dmr** [tiff/wysihtml5#345]
The change event gets fired once the user leaves the editor. Is there any event which fires right after the user entered something/pasted content?

**Comment by CurtisSV** [comment]
Somebody else asked a similar question, but nobody answered it yet. 

https://github.com/xing/wysihtml5/issues/348

**Comment by droopyd** [comment]
this seems to work. 
$((this.$('.wysihtml5-sandbox').get(0)).contentWindow.document).keyup(myListener);
where "this" is your view that contains the editor. I guess it can also be ommited.

but it's kinda hacky.
Would be nice to get some support.

**Comment by SirFizX** [comment]
Perhaps you can define this mess as a custom JQuery function like described here:
http://blogs.microsoft.co.il/blogs/basil/archive/2008/09/22/defining-your-own-functions-in-jquery.aspx

**Comment by selvagsz** [comment]
You could simply setup event listeners with jquery .on()

```
             $('.wysihtml5-sandbox').contents().find('body').on('keydown',function(event){
                // event handler here...
               // console.log(event);
              });
```

But it would be great if the editor supports these basic event delegations.

**Comment by dmr** [comment]
I don't know enough about the project and the roadmap (0.4?) to add this event so I'm going to close this, ok?

**Comment by peashutop** [comment]
thanks, @selvagsz! your solution worked for us.
others: see https://github.com/xing/wysihtml5/wiki/Events, towards the bottom, where there's a bit more elaboration on this solution.

the gotcha i just finally resolved: you need to make sure the wysihtml5 iframe is fully loaded before setting up this kind of listener.
