### ISSUE TITLE
Uneditable block

### ISSUE THREAD

**Issue by Neener54** [tiff/wysihtml5#36]
I've been attempting to create an item inside the editor that the only method the user has to edit it is through a menu.  I was able to get it somewhat working using a figure tag with contentuneditable="false" but the behavior was understandably flawed.  Is there a method for grouping a set of tags together in this manner?  This may be a outside of the scope of the editor.

**Comment by Neener54** [comment]
I've been reading up on this, it looks like I may attempt to continue along the figure with contentuneditable="false" path.  That sounds like it's working for other people in this situation.  Either way I'll reply with the solution I come up with for anyone that needs to accomplish the same functionality.

**Comment by Neener54** [comment]
So if anyone needs to do this all you have to do is make sure your rules are set up correctly (I just used a simple {} for the figure tag) then on the you'll have to declare contenteditable="false" for each child.  That works pretty well.  You can delete the whole block but not the individual parts.

**Comment by lucaspiller** [comment]
Actually any tag (e.g. `span`) will work for this. `span` is better as it has no default styling. `contenteditable` is a new HTML5 feature that can be applied to most tags - I'm not sure what support is like on older browsers however.

**Comment by drewB** [comment]
I think I am looking for the same thing but I am not entirely clear what you were trying to do.  Where you trying to setup the textarea to have a part of it that the user could not edit?  For example:

```
Enter your text here

*Can't edit this text*

Go ahead and edit this part
```

If so, could you give an example of how you set it up?

Thanks!
