### ISSUE TITLE
Removes Element Data in HTML

### ISSUE THREAD

**Issue by netweavemedia-nick** [tiff/wysihtml5#361]
Hey

I have just started using wysihtml5 for editing pages and I have found that it removes any element data when pasting into the text box.

So for example if i had an element <pre>&lt;p class=&quot;lead&quot;&gt;Test&lt;/p&gt;</pre> If i was to paste anything into the box it would just set the content to 

<pre>&lt;p&gt;Test&lt;/p&gt;</pre>

Is there a setting I need to change in order to stop it from doing this?

**Comment by Sam-Izdat** [comment]
Check out the [advanced parser rules page](https://github.com/xing/wysihtml5/blob/master/parser_rules/advanced.js) and the [getting started](https://github.com/xing/wysihtml5/wiki/Getting-Started) page. Basically, you have to add this class explicitly to the whitelist. If you want to keep inline styles, you will have to go with a fork like [this one](https://github.com/fac/wysihtml5/blob/master/test/dom/parse_test.js) and allow styles on the tags you want. Apparently, allowing styles is contradictory to the purpose of this project, from what I've gathered -- so you'd have to hack at it.
