### ISSUE TITLE
Why is a request to 'about:blank' triggered when the editor is initialized?

### ISSUE THREAD

**Issue by azolotov** [tiff/wysihtml5#38]
- I'm working on a Backbone app that allows you to edit different records.
- When you click on a new record, the form view for that record is rendered, containing 5 wysihtml5 textareas.
- At the same time 5 requests to `about:blank` are triggered that don't return anything.
- This causes the browser loading bar to flicker briefly, which I find annoying.
- I encountered this in on the following browsers on Max OS 10.7.3
  - Chrome 19.0.1084.9 dev
  - Chrome 17
  - Firefox 11
  - Safari 5.1.3

![](https://img.skitch.com/20120405-xu2t12wtsp738sjky1yu6abpr9.jpg)

What's that request for? Is there a way to suppress it?

**Comment by Neener54** [comment]
I believe this has something to do with the creation of the iframe. Not 100% sure though.

**Comment by tiff** [comment]
Hey @azolotov,

thanks for your investigation.

wysihtml5 creates an empty iframe (with no src set) which acts as the editor's sandbox.
This in fact seems to load the browser's empty default page: about:blank
My tests also show me that this is causing the loading bar to flicker shortly.

Right now I have no idea how to avoid that behavior but I'm open to suggestions...

**Comment by azolotov** [comment]
Is there any way to catch those requests before they are executed and just kill them?

**Comment by tiff** [comment]
This seems to fix the problem in Firefox but not Chrome:

``` javascript
var iframe = document.createElement("iframe");
document.body.appendChild(iframe);
iframe.contentWindow.stop();
```

Can you verify?

However it seems that the loading spinner is not only triggered by the iframe but also by the operation that creates a dom in it.

sandbox.js #161 (https://github.com/xing/wysihtml5/blob/master/src/dom/sandbox.js#L161)

``` javascript
      // Create the basic dom tree including proper DOCTYPE and charset
      iframeDocument.open("text/html", "replace");
      iframeDocument.write(sandboxHtml);
      iframeDocument.close();
```

**Comment by tiff** [comment]
Closing this as "won't fix" for now as I don't see any way to bypass the browser loading spinner.
