### ISSUE TITLE
IE9 Access denied

### ISSUE THREAD

**Issue by michaltaberski** [tiff/wysihtml5#388]
Hello,

I have (I think) quite basic use case where I am using wysihtml5.  However it doesnt work for IE9 at all. The problem is with `iframe.contentWindow` access. 
Precisely line:
**iframeDocument = iframe.contentWindow.document**

to give you a context where it happens small snippet below.

``` javascript

    _onLoadIframe: function(iframe) {
      // don't resume when the iframe got unloaded (eg. by removing it from the dom)
      if (!wysihtml5.dom.contains(doc.documentElement, iframe)) {
        return;
      }

      var that           = this,
          iframeWindow   = iframe.contentWindow,
          iframeDocument = iframe.contentWindow.document,
          charset        = doc.characterSet || doc.charset || "utf-8",
          sandboxHtml    = this._getHtml({
            charset:      charset,
            stylesheets:  this.config.stylesheets
          });

```

Do you have any idea? Wysihtml5 demo page works well on the same IE.

**Comment by michaltaberski** [comment]
Ok I know a bit more about possible reason of my problem. It's because of modification `document.domain`. Do anybody managed to have working `wysihtml5` with modifications like this?

I already tied to solve it by modifying iframe domain, but without any positive results. Any ideas?

**Comment by sandeepkashyap** [comment]
@michaltaberski were you able to find the solution?

**Comment by michaltaberski** [comment]
Yes. Finally I got it working. As I wrote before problem was related to `document.domain` setting.  Something like this fixed problem.

``` javascript

    _createIframe: function() {
      var that   = this,
          iframe = doc.createElement("iframe");

      var ie = window.navigator.userAgent.match(/MSIE\s/);
      if (ie) {
        iframe.src = 'javascript:(function () {' +'document.open();document.domain=\'' + document.domain + '\';document.close();' + '})();';
      };
[...]
```
