### ISSUE TITLE
Problem with placeholder

### ISSUE THREAD

**Issue by RicardoNeves** [tiff/wysihtml5#407]
I add a placeholder to the input but when i clear the input the placeholder doesn't show.

For example:
-Someone type "Hi!"
-Someone clicks on OK button
-On JS -> editor.clear(); // to empty the textarea.
-Input does not shown the placeholder, only empty textarea ...

Any help?

**Comment by michaelcode** [comment]
I to have this problem..

Any help please?

**Comment by RafaelAlba** [comment]
In case anyone stumbles upon this in the future, this is how I fixed it (note, this may not work for all versions. I looked through the source code to find this):

```
editor.clear()
editor.fire("set_placeholder")
```
