### ISSUE TITLE
Unbolding within a list jumps the content to a new list item

### ISSUE THREAD

**Issue by qrush** [tiff/wysihtml5#41]
Reproduced this here:

http://tifftiff.de/wysihtml5/examples/advanced.html

This probably happens with other actions inside of a list, but it's easily reproduced with just bolding. 

Hit bold, type something, start making a list. Make a list item with > 1 word, and then another one. 

![](https://img.skitch.com/20120412-mpkpt8hmr4888sw5by453dtauf.png)

Select one of the words from the first list item:

![](https://img.skitch.com/20120412-g91upgafd9w5g725j6ajgwi23n.png)

And after hitting bold again:

![](https://img.skitch.com/20120412-n5qpk8rgnifw6ksggw6sqrdaqr.png)

Jumps to the next line instead of staying on the current one, unbolded.

**Comment by tiff** [comment]
Thanks @qrush,

I'm able to reproduce it in Chrome (but not Firefox) and I already found a few ways to fix it. Still figuring out the best.

**Comment by tiff** [comment]
I think I fixed it, can you `make` and check whether it's really fixed for you? Thanks!

**Comment by qrush** [comment]
Fixed! Thanks!
