### ISSUE TITLE
Specify the text of a link createLink

### ISSUE THREAD

**Issue by jhollingworth** [tiff/wysihtml5#42]
A few people have requested the ability to specify the text of a link for bootstrap-wysihtml5 (https://github.com/jhollingworth/bootstrap-wysihtml5/issues/42). 

Does anyone see any issue's with adding an additional (optional) text property to the object passed in to the createLink command , e.g.

``` javascript
editorInstance.composer.commands.exec("createLink", { href: "http://google.com", text: "Google"});
```

If this makes sense to you guys I'm happy to implement it

Thanks,
James

**Comment by pstadler** [comment]
+1
