### ISSUE TITLE
node.nodeType

### ISSUE THREAD

**Issue by milnerm** [tiff/wysihtml5#425]
Getting the following error in FF23.0.1 and Chrome 28.0.1500 using wysihtml5-0.3.0.js and wysihtml5-0.3.0.min.js

TypeError: node is null
isElement       = node.nodeType === wysihtml5.ELEMENT_NODE,

on line 5990 in selectNode: function(node) {...

when the form is loaded. no typing. In FF it halts; in chrome, the code continues to work.

anyone? can't seem to find this anywhere in the existing issues.

**Comment by milnerm** [comment]
Nevermind... found the problem!

**Comment by kurtfunai** [comment]
@milnerm what was the issue? I'm running into it now
