### ISSUE TITLE
mailto not allowed

### ISSUE THREAD

**Issue by ilyakatz** [tiff/wysihtml5#427]
There was an issue about this https://github.com/xing/wysihtml5/issues/78 but looks like a few lines were missed

https://github.com/xing/wysihtml5/blob/master/dist/wysihtml5-0.4.0pre.js#L5065
https://github.com/xing/wysihtml5/blob/master/dist/wysihtml5-0.4.0pre.js#L5077

**Comment by agius** [comment]
Can't we pass a function to check_attributes or tags ? Or pass null / true / false to those attributes so they are not checked? Causing major headaches on our site :/

**Comment by miguelgraz** [comment]
I believe this situation could be a simple misunderstanding, to allow mailto links you can just say that your attribute can be `href`, as you can see here https://github.com/xing/wysihtml5/blob/master/dist/wysihtml5-0.4.0pre.js#L5088-L5089

It should work just like `src` or `url`, just allowing mailto along with other options.

**Comment by agius** [comment]
I want to allow other attributes as well, or have custom rules that are not in the set accessible by strings. Guess that's a separate issue.

**Comment by miguelgraz** [comment]
I see your issue @agius, and I agree with it. 
Indeed I believe this is a separate issue, hope my comment could help @ilyakatz a bit =)

**Comment by ilyakatz** [comment]
@miguelgraz yes, you're right. i figured it out after i created the issue. closing.
