### ISSUE TITLE
html format and indent

### ISSUE THREAD

**Issue by lalop** [tiff/wysihtml5#437]
Hello,
After used the wysihtml5 editor the raw html isn't really readable.
There's a way of controlling the html generated to add some indent and new lines ?

**Comment by r043v** [comment]
you can use style_html function from http://jsbeautifier.org/ to format the textarea content

**Comment by lalop** [comment]
thank for that, it works pretty well.
Here's my complete code :

``` javascript
editor.on('change_view', function(e){
  if(e == "textarea"){
    editor.synchronizer.editor.setValue(html_beautify($('#widget_custom_html_content').val(),{ indent_size: 2 }));
  }
});
```

I close the issue but if you think there a better way to do it...

**Comment by r043v** [comment]
for replace the content on view change i was used a custom new event, your way seen more regular :)
https://github.com/r043v/wysihtml5/commit/871cccc896b6032371724fd7ca57d81d00d2e434
