### ISSUE TITLE
Incorrect working on Heading text

### ISSUE THREAD

**Issue by mokaton** [tiff/wysihtml5#439]
Hi guys! Do you try to Heading your selected text in tests? If you are you will get that you editor heading all text of current line, not selected words. Look my screenshot below:

![wysihtml5](https://f.cloud.github.com/assets/4818055/1183845/f0dec8d8-2237-11e3-95cb-f2981cbd1106.png)

**Comment by stepansvoboda** [comment]
It is expected behavior. Headings are block elements so you cannot create **h1** from a word in the middle of the line.
