### ISSUE TITLE
Dynamically changing the css of the textarea

### ISSUE THREAD

**Issue by jiantongc** [tiff/wysihtml5#448]
Hi,

First of all, great plugin!

I'm currently experiencing an issue in changing the height of the textarea dynamically.
Steps:
1. http://xing.github.io/wysihtml5/examples/advanced.html
2. Modify the dom textarea (iframe)'s height attribute manually.
3. Focus the texarea -> All changed attributes are reverted

I'm working on an application where user can resize the container, and I need the wysihtml5's textarea inside to be resized as well, so that it matches the container size. 
The size has to be calculated to take care of other application-related controls.

I could hack the library easily by changing the BOX_FORMATTING variable, but I'm just wondering is there a better way to handle this situation?

Thanks in advance!

Cheers,
Jian

**Comment by simple10** [comment]
Hi @jiantongc. I ran into the same issue and used the following code to solve it without changing BOX_FORMATTING.

``` coffeescript
# coffeescript

editor = new wysihtml5.Editor(elem, options)

removeStyle: ($el, attr) ->
  re = new RegExp ";\\s*#{attr}:[^;]*;\\s*", 'g'
  $el.attr 'style', $el.attr('style').replace(re, '; ')

# Make sure everything has loaded before removing height attr
setTimeout =>
  @removeStyle($(editor.composer.focusStylesHost), 'height')
, 1
```

**Comment by jiantongc** [comment]
Thanks @simple10,
Nice, but this also means that we'll have to REMOVE and SET the height on resize, focus, etc...
I'd just set the min-height (and max-height) onResize (the only event that I'm interested), to cover up the height property, so that whatever height wysihtml5 set does not affect the output.

However I'm still hoping we could have a way to disable the the auto-update...
