### ISSUE TITLE
Current status of wysihtml5

### ISSUE THREAD

**Issue by jonchay** [tiff/wysihtml5#491]
Is this project still supported? I notice the number of issues and PRs, and the last commit on this repo was a year ago.

**Comment by Waxolunist** [comment]
I don't think so. I switched already to Edicy/wysihtml5

**Comment by jonchay** [comment]
Thanks for the update! Anyone wondering, this is the repo @Waxolunist was talking about:
https://github.com/Edicy/wysihtml5

**Comment by dhoulb** [comment]
I switched to **Edicy/wysihtml5** a while back too. He's made some great improvements.
