### ISSUE TITLE
Is this still actively developed?

### ISSUE THREAD

**Issue by swang** [tiff/wysihtml5#495]
Last merge was over a year ago...

**Comment by Waxolunist** [comment]
I changed to https://github.com/Edicy/wysihtml5
So no it is not.

**Comment by alvincrespo** [comment]
It doesn't seem like it :(

**Comment by dandv** [comment]
We've used this in [ggrc-core](https://github.com/reciprocity/ggrc-core) at Google. Bad choice.

What do folks recommend instead?
