### ISSUE TITLE
insertHTML & insertImage don't work before editor is clicked

### ISSUE THREAD

**Issue by iceton** [tiff/wysihtml5#50]
After editor is initialized, calling execCommand with insertHTML & insertImage don't work before you click in the iframe contentEditable area.

**Comment by tiff** [comment]
Thanks. Will look into this.

**Comment by codingwithoutcomments** [comment]
Did anyone find a work around for this?  Blocking issue.

**Comment by codingwithoutcomments** [comment]
Another Question: anyway to automate the clicking of the iframe contentEditable area?

**Comment by tiff** [comment]
I think this could work:

``` javascript
editor.focus();
editor.composer.commands.exec("insertHTML", "foobar")
```

I'll make sure that it works without having to focus it manually.

**Comment by codingwithoutcomments** [comment]
This works!  Thanks so much!

**Comment by codingwithoutcomments** [comment]
Correction, doesn't work on firefox.  Just works in Chrome :(

**Comment by raldred** [comment]
No problems in IE,Firefox,Chrome for me.
I'm using the following:

```
editor.currentView.element.focus();
editor.composer.commands.exec("insertImage", {"src":src,"alt":alt_text});
```

**Comment by Petah** [comment]
I thought execCommand had extreme cross browser differences. Is it the best way to go, why could you not detect the selection and then insert HTML via different, fully supported, methods? 

Raptor Editor (http://www.raptor-editor.com/) tries to avoid execCommand as much as possible.

**Comment by tiff** [comment]
@Petah I'm aware of the browser differences and documented some of them in a separate repository (https://github.com/tiff/wysihtml5-tests). That's why wysihtml5 is hardly using native execCommand. Instead it relies heavily on the selection api to do formatting.

@codingwithoutcomments Did you somehow managed to get it working in Firefox?

**Comment by raldred** [comment]
Hi David, wysihtml5 hardly uses the native execCommand, it mostly
implements its own. much like the alternative editor you suggested.

On 1 June 2012 12:19, David Neilsen
reply@reply.github.com
wrote:

**Comment by tiff** [comment]
@raldred Looks like someone had a deep look into the code. :) Awesome.

**Comment by Petah** [comment]
Loving your work, keep it up!

**Comment by raldred** [comment]
@tiff heh, been working on integrating into my jquery mobile app (aimed at desktop browsers),  been spending a bit of time reading the code learning how it all works so i can wire up custom dialogs for uploading images and other things.

Really impressed and very grateful for your hardwork.
If you're interesting how im using wysihtml5 & what im doing, heres a couple of shots.

https://docs.google.com/open?id=0B5i-3K7ouEzeN2wzenhicmxKcnc
https://docs.google.com/open?id=0B5i-3K7ouEzeb1gxTWZJTW0zdzg

(btw probably good to close this ticket now)

**Comment by codingwithoutcomments** [comment]
@tiff got it to work in ff!  thanks!

**Comment by tiff** [comment]
@codingwithoutcomments Thanks. I'm closing this one.
@raldred looks awesome. Be aware that there might be still some issues with iOS. (#62)

**Comment by LanFeusT23** [comment]
FYI this is happening to me on wysihtml5-0.3.0.min.js I'm unable to use insertHTML when using Firefox, as the .focus() won't ever focus in IE.

I've tried:
editor.focus();
document.getElementById("editorId").focus();
$("editorId").focus();
editor.currentView.element.focus();

none of the above work, works fine in Chrome and IE with the default editor.focus() though.

**Comment by digitaldevelopmentrevolution** [comment]
$('#CommentTextArea'+PostID).data("wysihtml5").editor.focus();
