### ISSUE TITLE
formatBlock h1 and h2 not working in IE11

### ISSUE THREAD

**Issue by yqgit** [tiff/wysihtml5#514]
The tags h1 and h2 are inserted only when the selected line is not the first of the textarea. When trying to make the first line of the textarea a header, nothing happens in IE11. I tested this in IE10/9/8 and seems to work fine.

**Comment by Waxolunist** [comment]
Have you tried this repo already: https://github.com/Edicy/wysihtml5

This is a still maintained fork of this repo. Xing does not maintain it anymore.

Just in case you are in search for a bootstrap implementation of this repo, try this one: https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg

**Comment by yqgit** [comment]
Thanks a lot!! The first repo solved my problem. The bootstrap one looks very nice, if only the project I'm working on had bootstrap!
