### ISSUE TITLE
Internet Explorer 11 Caret/Cursor problem

### ISSUE THREAD

**Issue by hakkisabah** [tiff/wysihtml5#530]
Hi everyone !
its my first issue !

i can learning some code php,jquery,css ..

and xing/wysihtml5 have a great code sequence.

But was internet explorer was some problem, i'm deal with this problem only , since one week :)

maybe its easy but i search too many code ! after try its my project. 

internet explorer caret position does not act naturally and taking to deal Immediately.. poffff...

but chrome and other browsers normal..

for example include in my post..

Thanks for any idea..

![chrome](https://cloud.githubusercontent.com/assets/10910670/6097438/66ec2990-afc6-11e4-9885-332563fa7731.png)
![internet explorer](https://cloud.githubusercontent.com/assets/10910670/6097439/66f01ec4-afc6-11e4-8da4-ea0e3161ba94.png)

**Comment by nelson6e65** [comment]
Did you read [README](https://github.com/xing/wysihtml5/blob/master/README.textile)? "This project isn’t maintained anymore. Please check out this [fork](http://wysihtml.com)".
