### ISSUE TITLE
Font-Size not Overriding

### ISSUE THREAD

**Issue by nebjor** [tiff/wysihtml5#556]
Hello, 
I recently asked this question on stackoverflow and got now answer. 

I have written a small web-app where you can edit documents via the wysihtml5 Editor, like on this site: [demo](http://wysihtml.com.)

after a few problems, quite everything worked fine, but now i recognized that when i change the font-size to 20 and put it back to 14 it still stays on font size 20 and both html-tags are used. Like this:

<span class="wysiwyg-font-size-20 wysiwyg-font-size-16">used font-size 20 at first. after i used 16, it still stays on 20.</span>

Anyone a clue what it could be?

original post: [overflow-question](http://stackoverflow.com/questions/38305945/wysihtml5-font-size-is-not-overriding-earlier-font-sizes)

**Comment by EvanBurbidge** [comment]
The demo link doesn't seem to be working. Getting a 404 page.
