### ISSUE TITLE
console log?

### ISSUE THREAD

**Issue by Charuru** [tiff/wysihtml5#57]
I get: Heya! This page is using wysihtml5 for rich text editing. Check out https://github.com/xing/wysihtml5

in my console.

That probably should not be.

There's no reason for me to use 2 versions of a script because my deployment process has a best in class minification process.

Thanks.

**Comment by tiff** [comment]
The console.log is intended. wysihtml5 is free software which has the right to advertise itself in the developer console. The  `console.log` won't break any functionality.

Other open source projects (Creative Commons) force their users to give credit on their website.

If you feel bad with it then execute `console.log = function() {};` somewhere before loading wysihtml5 but be aware that this might kill a kitten somewhere on this planet. :)

**Comment by Charuru** [comment]
I didn't realize it was intentional. Console log in production would cause javascript errors in many browsers. I really like this software though and am happy to promote it to developers I know.

**Comment by tiff** [comment]
The console.log is wrapped in a try/catch to avoid unwanted errors. :)

**Comment by jaybee** [comment]
You know, making this optional (defaulted to on) might be nice.

**Comment by tf** [comment]
But does it have to promote itself in my capybara poltergeist/phantomjs terminal output!? Really annoying.

**Comment by cknoxrun** [comment]
Old issue, but I'd just like to chime in. Yes it is free software, but if a developer needs something like this on their site, they will find a project based on _quality_ not an advertisement in the console log. In fact, I believe this turns people **off** the project. This is akin to adding Intel stickers all over a laptop. It's tacky and turns me off. Let the product speak for itself.

**Comment by lukaselmer** [comment]
+1

**Comment by itschn** [comment]
+1
