### ISSUE TITLE
Deleting a bullet in a list makes the text monospaced (cosmetic).

### ISSUE THREAD

**Issue by pygy** [tiff/wysihtml5#66]
If you delete a bullet in a list, the text that used to follow said bullet is displayed in a monospaced font.

It remains like this until you show the markup (which is normal) and come back to the editor.

Happens in Chrome 18, Ubuntu 11.04.

**Comment by joshmaker** [comment]
The same thing happens with paragraph tags. Delete the space infront of a paragraph and the text that follows it will become monospaced. Happens in Chrome 19 Mac OS X

**Comment by pygy** [comment]
I just looked at the DOM tree in the Chrome dev tools, in the list case, what used to be the second bullet is wrapped in a span with a hard coded monospaced font. 

I guess it's a debug tool that was left on.

**Comment by DavidBradbury** [comment]
Happening here as well (bullets and paragraph), Chrome 19 Windows 7.

Doesn't seem to happen in IE9 or Fx11/12 though.

**Comment by tiff** [comment]
Alright: That was really just an issue with the demo on the github page.
