### ISSUE TITLE
Support for <table>

### ISSUE THREAD

**Issue by rslinckx** [tiff/wysihtml5#68]
Is there any plans for supporting simple <table> markup in some ways ?

**Comment by tiff** [comment]
Hey @rslinckx there's currently no support for tables or more advanced formatting options planned. wysihtml5 should stay simple and only offer a few formatting options that generate the cleanest possible markup.

However you can try to insert a table with the following code and hope that this works for the user as expected:

``` javascript
yourEditor.composer.commands.exec("insertHTML", "<table><tr><td>content</td></tr></table>");
```
