### ISSUE TITLE
Please add image alignment and sizing :)

### ISSUE THREAD

**Issue by marcusgreenwood** [tiff/wysihtml5#69]
One function that (nearly) all WYSIWYG editors lack is simple image alignment and sizing tools. It would be really great if wysihtml5 had

a) Image resizing by dragging corners
b) Image alignment

Please see here for an example of how I think it should be done:
http://ghosted.it/demo

(Ghosted.it looked promising initially but the project appears to be dead)

**Comment by tim-peterson** [comment]
@marcusgreenwood just wanted to say thanks, i've been looking for solutions to dealing with images in a rich text editor, Ghosted.it looks pretty cool, thanks for the link, i'll try to contribute to wysihtml5 once I understand more about this codebase

**Comment by marcusgreenwood** [comment]
@tim-peterson awesome!

**Comment by tiff** [comment]
Hey @marcusgreenwood,

wysihtml5 already supports image alignment:
Check the advanced demo: http://xing.github.com/wysihtml5/examples/advanced.html (hit "insert image")

Also image resizing is supported (unfortunately not in Chrome or Safari as those browsers don't have such a feature implemented and I think it's not worth the effort to emulate that logic).

Cheers!

**Comment by tim-peterson** [comment]
@tiff thanks for the tip for aligning images in the advanced demo. I missed that. 

Not that its worth including in WYSIHTML5, but in my own app I may try to implement the image **resizing** as http://ghosted.it/ has done.  Shouldn't be too hard/too many lines of JS.

For responsive image sizes, it seems like waiting for what becomes of the `srcset` vs. `<picture>` debate could be useful: http://shallowthoughts.org/2012/05/17/img-srcset-vs-picture/

**Comment by marcusgreenwood** [comment]
FYI you can use this code (or something similar) to implement image resizing in webkit browsers:
http://www.editorboost.net/Webkitresize

I disagree that it's not worth the effort. Webkit is now the most popular browser (Hurrah!) and image resizing is an important feature.

**Comment by tim-peterson** [comment]
@marcusgreenwood good point, thanks for the link. Wow this looks like exactly what one could use! I'll check it out!

**Comment by tim-peterson** [comment]
For anyone interested, here's the complete code to use with the image resizing plugin suggested by marcusgreenwood (http://www.editorboost.net/Webkitresize ):

```
<script  type="text/javascript"  src="/path/to/jquery.js"></script>
<script  type="text/javascript"  src="/path/to/jquery.webkitresize.js"></script>
<script type="text/javascript" >
$(function(){
         $('.wysihtml5-sandbox').attr('id', 'simpleIFrame'); // $('.wysihtml5-sandbox') is the WYSIHTML5 <iframe>
        var iframe = document.getElementById('simpleIFrame');
        var doc = iframe.contentDocument || iframe.contentWindow.document;

        doc.body.innerHTML = iframe.textContent || iframe.innerHTML;

        if (doc.body.contentEditable) {
            doc.body.contentEditable = true;
        }

        var wrapImages = function () {
            $("#simpleIFrame").contents().find("img").each(function (i, img) {
                if (!$(img).parent().hasClass('image-wrapper')) {
                    $(img).wrap("<span class='image-wrapper'></span>");
                }
            });
        };
        /*
        Webkitresize can be initialized just with this code:
        $("#simpleIFrame").webkitimageresize().webkittableresize().webkittdresize();
        the reason why additional code was added is for adding image selection on click to this 
        example. When the editor is already doing this, which is true for CKEditor, TinyMCE and
        some of the Telerik editors, this additional code is not required.                
        */

       $("#simpleIFrame").webkitimageresize({
            afterReset: function () {
                wrapImages();
            },

            afterRefresh: function (img) {
                wrapImages();
            },

            afterElementSelect: function (img) {
                var range = iframe.contentWindow.document.createRange();
                range.selectNodeContents($(img).parent()[0]);
                var sel = window.getSelection();
                if (sel.rangeCount > 0)
                    sel.removeAllRanges();
                sel.addRange(range);
            }
        }).webkittableresize().webkittdresize();   

        if (!$.browser.webkit) {
            $("#browserError").html("<h1 style='color:red;'>Please note that the demo below was built for Webkit browsers like Chrome and Safari. For other browsers the pluging isn’t doing anything because IE and Firefox are providing their own image and table resize functionality</h1><br/>");
        }

    }); //doc.ready
```

_please note that this plugin doesn't work if you have applied the following box-sizing CSS rule_:

```
* { -moz-box-sizing: border-box; -webkit-box-sizing: border-box; box-sizing: border-box; }
```

**Comment by evadnoob** [comment]
Agree, another vote for image resizing with webkit.  http://en.wikipedia.org/wiki/Usage_share_of_web_browsers  Webkit based browsers have far more market than IE, 41% compared to 24%.

**Comment by gmoreira** [comment]
Did this ever get incorporated into the main codebase?

**Comment by tim-peterson** [comment]
Just realized people on this thread have been talking about two different things:

1) @tiff is correct in saying that image **alignment** is already part of WYSIHTML5.

2) However it appears that image **resizing** is NOT part of WYSIHTML5. 

@gmoreira, you can use the code I've shown above to do image resizing though it would be better if there was an integrated solution for both alignment and resizing.

Hey @tiff, note that the resizing plugin works in Firefox (v18.0) despite its claim of being Webkit specific.

Perhaps I or someone could make a pull request to adapt the image alignment dialog box to also include this resizing functionality?

**update** i've played a little more with the `webkitimageresize()` resizing plugin and realized that it injects `width` and `height` into the `style` attribute of the `<img>`. The problem is that it injects **pixel** widths/heights and NOT **percent**(%) based dimensions. So on mobile browsers vs. desktop browsers this UI issue would need to be addressed.
