### ISSUE TITLE
classes become inline styles in chrome

### ISSUE THREAD

**Issue by alissaVrk** [tiff/wysihtml5#7]
in chrome, when you 
add a css class to the whole text, delete all of it and start writing again
write a few lines, add a class to them, make a list of the
and probably other scenarios
the classes become inline styles..

**Comment by tiff** [comment]
This definitely seems to be an issue.
http://stackoverflow.com/questions/8332245/contenteditable-in-chrome-and-safari-replaces-css-classes-and-rules-with-inline

Will look into this.

**Comment by tiff** [comment]
Hah, just recognized that you're the author of that question on stackoverflow...

**Comment by tiff** [comment]
Hey alissaVrk,

I hope this isn't happening anymore.
The people at WebKit/Chrome overhauled a lot of rich text editor logic. Check http://www.webkit.org/blog/1737/apple-style-span-is-gone/
Feel free to reopen/comment if this is still happening in a browser (that is up-to-date).
