### ISSUE TITLE
Paginating wysihtml5 documents for use in a content slider 

### ISSUE THREAD

**Issue by tim-peterson** [tiff/wysihtml5#71]
I'm just starting to look at wysihtml5, but is there a way to paginate word documents or pdfs that have been cut and pasted into the text editor?

Would require a simple `wrap()` function dividing the text/images at given height/width intervals, yes/no?

tim

**Comment by tiff** [comment]
Hey @tim-peterson,

I'm afraid this feature is a bit too advanced for wysihtml5.
wysihtml5 v0.4 will come with an option to make wysihtml5 auto-growing to fit its content.

**Comment by tim-peterson** [comment]
hi @tiff, thanks for the heads-up that v0.4 will incorporate auto-growing. That will be quite nice. In the meantime, i'll try to contribute to developing pagination. I'm still a beginner/intermediate JS guy so I don't expect miracles, but I really like this plugin so would like to help it grow!

**Comment by tiff** [comment]
Looking forward!

**Comment by tim-peterson** [comment]
Here's a [Stackoverflow Q&A](http://stackoverflow.com/questions/11277529/wrap-text-every-2500-characters-in-a-div-for-pagination-using-php-or-javascrip) I posed that might help as a starting point for paginating wysihtml5 pages.

Please look at the [answer and JSFiddle provided by Eric](http://jsfiddle.net/Eric/WTPzn/) which is really excellent.

**Comment by tim-peterson** [comment]
Going deeper on this pagination idea I'm trying to figure out if I can make wysihtml5 compatible with a content slider. 

My preference is to integrate with deck.js since [deck.js](https://github.com/imakewebthings/deck.js) is a really well-executed and popular content slider. Try it out on mobile or desktop, demo: http://imakewebthings.com/deck.js/, it is really slick.

Anyway, i'm working on this integration now on my site and would love people's thoughts on this...
