### ISSUE TITLE
Colors not working in Opera 11.61

### ISSUE THREAD

**Issue by sgraffite** [tiff/wysihtml5#74]
When I highlight text using Opera 11.61, and then click on the color selection dropdown and choose a color, the text does not change color.  I do see it shift slightly as if it had been wrapped with a new element, but no color change occurs.

I tested in FireFox and Chrome just to make sure I was doing it properly, and both of those correctly changed the color.

**Comment by tiff** [comment]
Damn. Will check over the next days.

**Comment by NWSE-ICO** [comment]
Cannot reproduce in Opera 11.62 and 11.64 Opera/9.80 (Macintosh; Intel Mac OS X 10.6.8; U; de) Presto/2.10.229 Version/11.64

**Comment by tbind** [comment]
Colors seems not working in any browser (tested with Firefox 12.0, Safari 5.1.7, Chrome 19 in OSX 10.7.3).

With this html code :

``` html
<!doctype html>
<head>
    <title> Test Wysihtml5 </title>

    <script src="js/wysihtml5-0.3.0.min.js"></script>
    <script src="js/parser_rules/advanced.js"></script>
</head>
<body>
    <div id="wysihtml5-toolbar" style="display: none;">
      <a data-wysihtml5-command="bold">bold</a>
      <a data-wysihtml5-command="italic">italic</a>

      <!-- Some wysihtml5 commands require extra parameters -->
      <a data-wysihtml5-command="foreColor" data-wysihtml5-command-value="red">red</a>
      <a data-wysihtml5-command="foreColor" data-wysihtml5-command-value="green">green</a>
      <a data-wysihtml5-command="foreColor" data-wysihtml5-command-value="blue">blue</a>

      <!-- Some wysihtml5 commands like 'createLink' require extra paramaters specified by the user (eg. href) -->
      <a data-wysihtml5-command="createLink">insert link</a>
      <div data-wysihtml5-dialog="createLink" style="display: none;">
        <label>
          Link:
          <input data-wysihtml5-dialog-field="href" value="http://" class="text">
        </label>
        <a data-wysihtml5-dialog-action="save">OK</a> <a data-wysihtml5-dialog-action="cancel">Cancel</a>
      </div>
    </div>
    <form>
        <textarea id="wysihtml5-textarea" placeholder="Enter your text ..." autofocus></textarea>
    </form>

    <script>
        var editor = new wysihtml5.Editor("wysihtml5-textarea", { // id of textarea element
          toolbar:      "wysihtml5-toolbar", // id of toolbar element
          parserRules:  wysihtml5ParserRules // defined in parser rules set 
        });
    </script>
</body>
</html>
```

**Comment by NWSE-ICO** [comment]
@tbind see how the line 
<code>stylesheets:  "css/stylesheet.css",</code>
handles the CSS in the advanced example. Does that fix your issue?

**Comment by sgraffite** [comment]
I didn't realize there were different demos when I reported this, so to clarify I am experiencing the bug in Opera 11.61 on this demo: http://xing.github.com/wysihtml5/

The color changing in this demo works properly  for me in Opera 11.61: http://xing.github.com/wysihtml5/examples/advanced.html

I am running Windows 7 with SP1 in case that is important.  Hope this helps.

**Comment by tbind** [comment]
@ingochao Yep it's ok for me, thx ;)

**Comment by tiff** [comment]
@sgraffite I also tested it on Opera 11.61 (OSX Snow Leopard) and wasn't able to reproduce it either. Sorry.
