### ISSUE TITLE
Enter after first normal line scroll down one line in Chrome

### ISSUE THREAD

**Issue by jcubic** [tiff/wysihtml5#75]
If you change first line in demo to normal (uncheck H1) when you hit enter after first line it scoll down one line, so it look like your text dissapear. (tested in Chromium 18 on Ubuntu).

**Comment by NWSE-ICO** [comment]
@tiff Confirmed in Chrome Mac, and yes, this is unexpected/annoying. Why is that thing scrolling to a position that is already visible?

**Comment by tiff** [comment]
Bug. Will take care. Thanks.

**Comment by tiff** [comment]
This is now fixed in master (not yet deployed to the demo page as the demo needs a stable release)
