### ISSUE TITLE
Deleting a <li> wraps following text in strange span

### ISSUE THREAD

**Issue by dlee** [tiff/wysihtml5#76]
When you select across a `<li>` element or multiple `<li>` elements and delete, it concatenates the following text by wrapping the text in a strange monospaced span tag: `<span style="background-color: rgba(0, 0, 0, 0); font-family: 'Courier New', Courier, monospace; line-height: normal; ">`.

I'm using Chrome 19 on OSX Lion.

**Comment by tiff** [comment]
That was an issue with the github page demo. Thanks for reporting. Has been fixed.
