### ISSUE TITLE
Allow "mailto" in anchor href attribute

### ISSUE THREAD

**Issue by barrypitman** [tiff/wysihtml5#78]
This is the regex used for validating URLs (under attributeCheckMethods):

``````
    url: (function() {
      var REG_EXP = /^https?:\/\//i;
      return function(attributeValue) {
        if (!attributeValue || !attributeValue.match(REG_EXP)) {
          return null;
        }
        return attributeValue.replace(REG_EXP, function(match) {
          return match.toLowerCase();
        });
      };```
    })(),

Please include mailto: links in the allowable formats:

```var REG_EXP = /^[https?:\/\/|mailto:]/i;```
``````

**Comment by ErneX** [comment]
+1

**Comment by goodtune** [comment]
Why not any scheme such as ftp, gopher, etc?

**Comment by tiff** [comment]
Fixed with c01afc800a20a0e9a0fbbb189c85f81a1b5310d7

**Comment by tiff** [comment]
I did some more changes concerning this logic to also support absolute paths. see 4a153a832f19733c2b1a6f5c24ae2266e5b67569 and 54959a7e0c16382e390f20a9775e91abab9316fc

**Comment by p3sn** [comment]
Is it possible to exclude 'a href' for modifying in advanced.js ?  That would solve my problem for auto-changing mailto: links into something else.
