### ISSUE TITLE
undo moves cursor location

### ISSUE THREAD

**Issue by JosephLenton** [tiff/wysihtml5#81]
In Firefox 12 on Windows 7.

If I type in text, and then ctrl+z to undo, I find the cursor moves to the bottom of the page. It also deselects if I delete a list item, and then undo this.

**Comment by tiff** [comment]
Thx will look into this!

**Comment by tiff** [comment]
Ok, I can reproduce this and started working on fixing this in the "undo_manager_fix" branch (https://github.com/xing/wysihtml5/tree/undo_manager_fix)
