### ISSUE TITLE
Cursor handling

### ISSUE THREAD

**Issue by ghost** [tiff/wysihtml5#83]
The biggest problem with the editor is that there is no cursor logic. If I decide to insert a DIV, pressing the DEL will automatically delete the markup. WHY? If I insert a table at the top, how can I escape the table?

**Comment by tiff** [comment]
Hi @dixflat,

I personally don't see any problems with the cursor handling.
Tables are not supported by the editor currently.

I don't have any intents to build a special cursor interaction logic for wysihtml5 as I think browsers already do a pretty good job at that.

**Comment by ghost** [comment]
Then insert the following into the code in html view:

<div>I'm so happy</div>


move the cursor before the I'm so happy section in html view and press del.... watch as the <div> markup disappears. That's the problem.
