### ISSUE TITLE
Nested lists

### ISSUE THREAD

**Issue by brycecammo** [tiff/wysihtml5#84]
It would be nice to be able to create nested ul/ol elements. Pressing tab while in a ul/ol would add another 'level'. For example:
- level 1
  - level 2
- level 1 again

P.S. Great job with wysihtml5 - it was just what I was looking for :)

**Comment by tiff** [comment]
This is definitely planned to be part of wysihtml5. There's already a pull request by @qrush waiting for review: https://github.com/xing/wysihtml5/pull/53

**Comment by brycecammo** [comment]
So apparently I need to learn how to use the search feature :)

**Comment by tiff** [comment]
Duplicate of #53
