### ISSUE TITLE
Markdown Support

### ISSUE THREAD

**Issue by tomgiles** [tiff/wysihtml5#86]
Support for markdown would make this editor even more awesome...

**Comment by tiff** [comment]
Thanks @tomgiles I don't think that this feature will ever become part of wysihtml5. However I could think of a "wysimarkdown" fork/plugin. Go! :)

I think all it needs is a html2markdown/markdown2html converter to be built in.

**Comment by ForbesLindesay** [comment]
I'm inclined to suggest a totally separate project with a separate function to do the two way conversion, rather than a fork of this project, may implement this myself if I get time at some point (give me a few weeks)

**Comment by hadees** [comment]
So i've been looking into writing "wysimarkdown" fork/plugin.  So far it looks like [Pandoc](http://johnmacfarlane.net/pandoc/) would be the best choice and could in fact make wysihtml5 work with a ton of other formats.

The real issue I see is that all of this would have to happen server side which makes writing a concise plugin difficult.

I'm kind of secretly hoping minds get changed and wysihtml5 will support it. :smiley: 

Edit:

So scratch that [leeoniya/reMarked.js](http://github.com/leeoniya/reMarked.js) looks way more promising.
