### ISSUE TITLE
Downloading specific tool from wysihtml5

### ISSUE THREAD

**Issue by acebo** [tiff/wysihtml5#87]
wysihtml5 is a very cool texteditor plugin with many tools, but is it possible to only get the tool that I want from wysihtml5 such as bold and italic? then download those small files separately like you would in jquery ui.

thank you :)

**Comment by tiff** [comment]
Hey @acebo  :)

I'm afraid that this isn't easily possible.
The toolset wysihtml5 offers is deeply nested into the core so it would require a lot of work to modularize this (which is imho not worth the effort).
Also wysihtml5 is already very tiny in terms of file size (compared to other editors).

If you want you can strip out unnecessary code and build your own wysihtml5 editor. Just hit "Fork" :)
Contact me if you need help.

**Comment by acebo** [comment]
I thought so, I might think about it if I really should do it. 

Thanks for the response though. :)
