### ISSUE TITLE
Getting-Started should include a step for styling

### ISSUE THREAD

**Issue by NWSE-ICO** [tiff/wysihtml5#88]
https://github.com/xing/wysihtml5/wiki/Getting-Started does not link a stylesheet and does not use the stylesheet configuration option. This may leed to the impression that the colors don't work.

**Comment by tiff** [comment]
True. Will add that.
@ingochao If you want you can add that point by yourself. Wiki pages are free for anyone to be edited.

**Comment by NWSE-ICO** [comment]
@tiff ok done, please check if it is appropriate.

**Comment by tiff** [comment]
Thank you! Looks good.
