### ISSUE TITLE
Pasting in html mode

### ISSUE THREAD

**Issue by sud0n1m** [tiff/wysihtml5#91]
Pasting a url after first writing`<a href="` causes the line to be deleted. This also happens with `<img src="`. This makes it difficult to write HTML manually.

For example, we're using WYSIHTML5 to compose emails, and one of the requirements is to use tables to position images left and right (ugh). But to do that, you'd have to edit in HTML mode. Right now it's possible to workaround, but a little cumbersome that the line gets deleted.

**Comment by tiff** [comment]
Valid point. Will fix. Thanks for reporting.

**Comment by tiff** [comment]
Has been fixed with 82d3a0eac002e551244a678f0ca44c8f16402f02
