### ISSUE TITLE
BBCode Parser

### ISSUE THREAD

**Issue by shibulijack** [tiff/wysihtml5#92]
Is it possible to generate BBCode using a custom parser?

P.S: 
I don't know if this is the correct place to post this question. Sorry.

**Comment by raldred** [comment]
This sort of thing seems like it might be out of scope for wysihtml5

**Comment by Petah** [comment]
Why would you want BBCode? Could you not just support a limited subset of HTML?

**Comment by tiff** [comment]
I agree with @raldred and @Petah.

Here's how you could implement BBCode:
1. Find a good BBCode2HTML/HTML2BBCode Converter (written in JavaScript)
2. Find out when the user switches to the source code view ([change_view event](https://github.com/xing/wysihtml5/wiki/Events)) and transform the html generated from wysihtml5 into BBCode and update the textarea
3. When the user switches back to rich text mode transform the BBCode into HTML
4. When the user submits the form transform the result to BBCode before it reaches the server

Ping me if you need any help.
