### ISSUE TITLE
Copying width/height styles and setting html width/height breaks in flexible box model

### ISSUE THREAD

**Issue by zdennis** [tiff/wysihtml5#93]
Removing width and height from RESIZE_STYLE and BOX_FORMATTING fixes an issue where the iframe was improperly getting sized when used with flexible box model.

It would be great to turn these off or detect if inside of a flexible box model and to not copy them.

**Comment by NWSE-ICO** [comment]
please describe the problem in more detail, would be great to have an example. 

The CSS WG is actively editing the spec, it is a fast moving target. http://dev.w3.org/csswg/css3-flexbox/

**Comment by tiff** [comment]
I revised the entire styling logic for v0.4 (you can compile/`make` the current master and check by yourself). It should have been fixed now. However if you wanna omit the copying of styles from the `<textarea>` to the editor then set config option `style`to `false`.
