### ISSUE TITLE
MathJax support

### ISSUE THREAD

**Issue by saptarshiguha** [tiff/wysihtml5#95]
Not really an issue, but do you have plans on incorporating MathJax support? say I start typing and then press '$', upon the closing $, the editor would submit it to MathJax.

No idea if this can be done, just asking.

Thanks 
S

**Comment by tiff** [comment]
Hi @saptarshiguha I don't think that this could be useful for the average user. You can build your own hook by listening to the keydown event. I'd be happy to support you.
