### ISSUE TITLE
Can't type on iOS

### ISSUE THREAD

**Issue by ThomasBerends** [tiff/wysihtml5#98]
I can't type on iOS. I can remove text, and style it. But I can't enter any text in the text field.

iOS 5.1.1
iPad 2 3G
iPhone 4S

**Comment by sstephenson** [comment]
I believe this is an iOS bug—if you have any `touchstart`, `touchmove`, `touchend`, or `touchcancel` event handlers registered, you won't be able to type in a contenteditable field after repositioning the cursor.

**Comment by ThomasBerends** [comment]
Is there any workaround? I tried typing at  the demo, but I couldn't get it to work.

**Comment by NWSE-ICO** [comment]
Prior to iOS 5.1.1 it worked for me. Now, with 5.1.1, the cursor sometimes flips away.  The keypad is visible then, but you cannot see the input. But only sometimes. Seems to be more stable if you start with the html view and then switch to the wysiwyg view. After that, typing in seems to work.

**Comment by tiff** [comment]
Just installed ios 5.1.1 on my ipad, will check this.

**Comment by JonFabritius** [comment]
On a site I'm building, which uses custom touch event detection, the text caret sometimes fails to appear. (Using the same HW/SW configuration as above.)

Input always shows up, though. Hiding the keyboard a few times brings the cursor back.

**Comment by tiff** [comment]
I'm not able to reproduce any of the issues with my iPad 1 (iOS 5.1.1) and the current master.
I know that wysihtml5 is in use at the mobile site of a big company and they say everything works as expected.

Please reopen if you still experience any problems.

**Comment by markbrown4** [comment]
I'm experiencing the same issue as outlined.  If you tap in the editor you can type away but if you hold(make a selection) it won't add new content, only backspace allows deleting content.

Sam's tip off does fix the issue as well, I was using select2 and ios-orientation-fix which register these events.  Removing those scripts resolved it for me.

Any ideas for how to work around this bug?

This is occurring in the latest version of iOS.

**Comment by JonFabritius** [comment]
The guys at Codepen.io ran into a spesific iOS textarea text entry issue, that was caused by setting the border of the textarea to a 0 width. http://blog.codepen.io/2013/03/05/better-ios-support/

**Comment by ThomasBerends** [comment]
That is not related to this problem as far as I know.
Met vriendelijke groet,

Thomas Berends

— Sent from Mailbox for iPhone

**Comment by haroonxml** [comment]
any update on this ? I am getting the same issue on IOS 6.1.3.

**Comment by AndrewRayCode** [comment]
I am getting this too on an iPhone, but I don't get it when I visit the demo page for this site. I'm including jquery mobile on our page which probably binds to to the events you suspect are problematic.

The exact behavior is you can type in the editor, but if you hit done and go back in to type again, it only lets you delete text, not re-enter it.

**Comment by AndrewRayCode** [comment]
Here is a test page that includes jQuery mobile along with the editor:

http://andrewray.me/stuff/wysihtml5/examples/advanced.html

It displays the behavior, eg if you type in the editor, then click outside the editor (I made the main page green for easy clicking), then click back in, it will stop you from typing more characters. It's a little flaky to trigger but it definitely happens. You might also be able to trigger it by hitting "Done" iPhone button and then refocusing.

The only changes I made to the page, other than background color, was:

```
<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
```

The editor does not play well with jQuery mobile out of the box, so I suggest reopening this issue.

**Comment by AndrewRayCode** [comment]
ping @tiff  @sstephenson

**Comment by anacarolinats** [comment]
I am getting this too. Someone found an workaround?

**Comment by AndrewRayCode** [comment]
Ping @xing fix your year old bug ;)

**Comment by mparramont** [comment]
I'll try to research this tomorrow :)

**Comment by haroonxml** [comment]
I resolved the problem by moving wysihtml5 control to a new page on its own. The page it was in before was very busy with a lot of elements. Moving the control resolved the issue.  I know its not a very scientific answer but  that's what worked for me.

**Comment by mparramont** [comment]
We're getting a new maintainer for this library. I'll post more info soon.

**Comment by AndrewRayCode** [comment]
@mparramont @xing @sstephenson "soon" :)

**Comment by haroonxml** [comment]
Sorry i lied, I was told this morning that the control on a new page on its own still has issues.

**Comment by jonpincus** [comment]
i'm having this problem too, on various flavors of iOS.

**Comment by dmr** [comment]
> We're getting a new maintainer for this library. I'll post more info soon. 

@mparramont @xing @sstephenson "soon"?

**Comment by imskull** [comment]
I found the reason: this issue occurs when iframe.contentWindow get blurred but iframe's body still focus,  in the case iOS keyboard will not disappear, it looks like you are able to input, indeed you can't.

a dirty workaround, insert following  code after your "var editor = new wysihtml5.Editor...":

editor.composer.element.ownerDocument.addEventListener("touchstart", function() {
    setTimeout(function() {
        editor.composer.iframe.contentWindow.focus();
    }, 500); // do not use 0, window will get blur in a short time after touchstart.
});

beware: there are many cases will cause contentWindow get blurred, if you find you can't input after press button on toolbar, or something like this, you should call
"editor.composer.iframe.contentWindow.focus();" as well. good luck!

**Comment by kelvinlouis** [comment]
@Imskull I love you! We use Quill.JS, but this approach worked like a charm for us!

**Comment by marr** [comment]
Any updates to this bug?

**Comment by Waxolunist** [comment]
@marr Did you look into a still maintained fork of this repository, e.g. http://edicy.github.io/wysihtml5/ Maybe its resolved there. And if not, report the bug there. The chances are better, that it will fixed in the fork.

**Comment by prud** [comment]
@Imskull good job, thanks for sharing this

I'm using this with a slight improvement. Instead of listening to each and every touchstart, I listen for blur events on the iframe.

**Comment by jeff-ph** [comment]
@Imskull Thanks for the solution, this may just resolve the issues I've been trying to debug off and on for 2 weeks! This solution also appears to be valid from within the document being loaded into the iframe:

@prud I'm curious how you are just listening for blur events on the iframe in order to restore focus to it when necessary -- how are you determining when the iframe should be given focus again vs. when it has legitimately lost focus and should not get it back?
