### ISSUE TITLE
using createLink but skipping the dialog throws an error ie IE9

### ISSUE THREAD

**Issue by haggen** [tiff/wysihtml5#99]
I made a custom dialog for creating an anchor since my needs were very specific. But I did not used the bindings for dialog, I just bound to my OK button the following call and everything works fine in Firefox and Chrome.

```
editor.composer.commands.exec('createLink', { href: value }); // value has the url I want to use
```

But when I tested in IE9 it thorws an error:

```
SCRIPT87: Invalid argument. 
wysihtml5.js, line 6003 character 7
```

The passage mentioned is inside the method `setAfter`:

```
setAfter: function(node) {
  var range = rangy.createRange(this.doc);
  range.setStartAfter(node); // Specificaly this line (6003)
  range.setEndAfter(node);
  return this.setSelection(range);
},
```

I'm going to debug the code, but I already got a hunch; it may have something to when the rte tries to recover the saved selection. Since I skipped the dialog call, I assume no selection was saved and then it's trying to reference a null variable or something like that.

**Comment by haggen** [comment]
As I suspected, when I skip the dialog bindings and call `createLink` directly from a button, `node` inside `setAfter` comes `undefined`.

I need a manual call for save/restore RTE selection.

Update. Found it.

```
var bookmark = editor.composer.selection.getBookmark();
editor.composer.selection.setBookmark(bookmark);
```

It worked.

**Comment by eric-wood** [comment]
I'm having a similar issue, but on the 0.4.0pre version. I think I understand your solution, but where are you calling the code that fixes the problem?

**Comment by haggen** [comment]
@eric-wood One of the first things I do inside the `click` event callback. My code is a lot more complex because of a lot more features but, I'll try to emulate the important parts here:

``` javascript
var editor = ...; // get the wysihtml5 instance

$('a.createLink').on('click', function(e) {
  var bm = editor.composer.selection.getBookmark();

  //...

  editor.composer.selection.setBookmark(bm);
  editor.composer.commands.exec('createLink', '...');
});
```

I can't remember exactly what I did but I think the problem happens when the user loose focus on the editor. The bookmark fixes it by refocusing it.

**Comment by eric-wood** [comment]
Thanks for getting back to me so quickly!

You were right, it was an issue with adding focus back to the editor before executing the command!

Rather than doing the bookmark hack, I found that this worked:

``` javascript
editor.focus();
editor.composer.commands.exec("createLink", ...);
```

I owe you a beer :beer:

**Comment by haggen** [comment]
Hahah no problem man, you're welcome. But tell me something, simply calling `focus()` did recover the user's selection ?

**Comment by eric-wood** [comment]
It loses the cursor position, which is becoming a problem now (didn't notice it before...), even when I call `focus()` followed by `setBookmark(bm)`, so I'm trying to figure out how to get around it all.

Removing the call to focus breaks it all, though.

UPDATE: this was my fault for not grabbing the bookmark early enough. When the contenteditable loses focus, IE resets the caret to the beginning, which ruined everything. Grabbing the bookmark before showing the modal solved all my problems.
